In [1]:
# importing relevant libraries
import pandas as pd
import numpy as np
import json
import os
from itertools import chain

# import boto3

from tqdm.notebook import tqdm_notebook
import time

import csv
import re

# display all rows & columns
#pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# show all outputs
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

# Disable warnings
import warnings
warnings.filterwarnings("ignore")

**Import data for analysis**

In [2]:
# Import data
attrition_list = 'Hopeliner Copy of Sample 2022 Attrition List.xlsx'
responses = 'TTEC Interviews (Responses).xlsx'

attrition_df = pd.read_excel(attrition_list)
response_df = pd.read_excel(responses)

**Pre-processing of Dataset**

In [3]:
# Strip column names
attrition_df.columns = [x.strip() for x in attrition_df.columns]
response_df.columns = [x.strip() for x in response_df.columns]

# Response df - pre-processing
response_df.rename(columns =  {'Read Call Opening: \nHi (First Name), thank you for making time for this short interview or chat with us. As shared in our (email/ SMS) exchange, my name is (Interviewer Name). I am from e-BI Solutions. We are working with TTEC to find ways to improve their employee experience so we are grateful that you made time for this.':'Read Call Opening',
                              'Confidentiality Notice and Consent:\nPlease note that we will treat our conversation with confidentiality and only disclose information to the extent you wish to share them with TTEC. Our goal is to help them improve the employee experience through an unbiased study and analysis of the data we gather. We will ask for your sign-off on the final notes we will include in the study. Do you agree and consent to this interview/ short chat? (Share option to record video/ audio/ transcript only)\n\n(Wait for response. Proceed with questions as appropriate)': 'Confidentiality Notice and Consent',
                              }, inplace = True)

cols = ['Stated Reason for Leaving TTEC', 'Other considerations for leaving', 'Top 3 Low lights and impact to them',
'Highlights of their stay with TTEC', 'Suggestions on redesigning the experience',
'What would make you consider returning or referring friends and family members to TTEC?',
'Any questions for e-BI or TTEC?']

for col in cols:
    response_df[col] = response_df[col].astype(str)
    
# Add a new column for all reasons for leaving
response_df['All Leaving Reasons'] = response_df['Stated Reason for Leaving TTEC'] + " " + response_df['Other considerations for leaving']

## Pre-processing Descriptive Data

In [4]:
# pip install gensim
# pip install nltk
# pip install matplotlib
# pip install advertools
# Run 'python -m nltk.downloader all' on ubuntu
# pip install typing-extensions --upgrade

In [5]:
#import modules
import nltk
import gensim
import advertools as adv
import matplotlib.pyplot
import os.path
from gensim import corpora
from gensim.models import LsiModel
from nltk.tokenize import RegexpTokenizer
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from gensim.models.coherencemodel import CoherenceModel
import matplotlib.pyplot as plt

# Latent Dirichlet Allocation (LDA) Topic Analysis Model

**Resources:**
- [Evaluate Topic Models: Latent Dirichlet Allocation (LDA)](https://towardsdatascience.com/evaluate-topic-model-in-python-latent-dirichlet-allocation-lda-7d57484bb5d0)

- [pyLDAvis: Topic Modelling Exploration Tool That Every NLP Data Scientist Should Know](https://neptune.ai/blog/pyldavis-topic-modelling-exploration-tool-that-every-nlp-data-scientist-should-know)

In [6]:
from gensim.utils import simple_preprocess
from nltk.corpus import stopwords

# Stop words
stop_words = stopwords.words('english') + list(adv.stopwords['tagalog'])

# Functions
def sent_to_words(sentences):
    for sentence in sentences:
        # deacc=True removes punctuations
        yield(gensim.utils.simple_preprocess(str(sentence), deacc=True))
        
def remove_stopwords(texts):
    return [[word for word in simple_preprocess(str(doc)) 
             if word not in stop_words] for doc in texts]

def preprocess_data_indiv(doc_set):
    """
    Input  : docuemnt list
    Purpose: preprocess text (tokenize, removing stopwords, and stemming)
    Output : preprocessed text
    """
    # initialize regex tokenizer
    tokenizer = RegexpTokenizer(r'\w+')
    # create English & Tagalog stop words list
    en_stop = set(stopwords.words('english') + list(adv.stopwords['tagalog']))
    # Create p_stemmer of class PorterStemmer
    p_stemmer = PorterStemmer()
    # list for tokenized documents in loop
    texts = []
    # loop through document list
    for i in doc_set:
        # clean and tokenize document string
        raw = i.lower()
        tokens = tokenizer.tokenize(raw)
        # remove stop words from tokens
        stopped_tokens = [i for i in tokens if not i in en_stop]
        # stem tokens
        #stemmed_tokens = [p_stemmer.stem(i) for i in stopped_tokens]
        # add tokens to list
        texts.append(stopped_tokens)
    return texts

In [7]:
# NLTK Stop words
# import nltk
# nltk.download('stopwords')
from nltk.corpus import stopwords
stop_words = stopwords.words('english') + list(adv.stopwords['tagalog'])
stop_words.extend(['from', 'subject', 're', 'edu', 'use','employee','ttec','resign'])
# Define functions for stopwords, bigrams, trigrams and lemmatization
def remove_stopwords(texts):
    return [[word for word in simple_preprocess(str(doc)) if word not in stop_words] for doc in texts]
def make_bigrams(texts):
    return [bigram_mod[doc] for doc in texts]
def make_trigrams(texts):
    return [trigram_mod[bigram_mod[doc]] for doc in texts]
def lemmatization(texts, allowed_postags=['NOUN', 'ADJ', 'VERB', 'ADV']):
    """https://spacy.io/api/annotation"""
    texts_out = []
    for sent in texts:
        doc = nlp(" ".join(sent)) 
        texts_out.append([token.lemma_ for token in doc if token.pos_ in allowed_postags])
    return texts_out

In [8]:
# Create a copy of the original response dataframe
analysis_df = response_df.copy()

> 1) Remove punctuations, digits and stop words from text

In [9]:
# Remove punctuations & digits
import re
from string import digits
remove_digits = str.maketrans('', '', digits) # remove digits

for col in cols:
    analysis_df[col] = analysis_df[col].apply(lambda x: re.sub(r'[^\w\s]', '', x).translate(remove_digits).strip().lower())

In [10]:
import spacy
# !python -m spacy download en_core_web_lg 
# !python -m spacy download en_core_web_sm

In [11]:
# Remove stop words
data = analysis_df['Other considerations for leaving'].to_list() # field to analyse (MANUAL INPUT)
data_words = list(sent_to_words(data)) # convert words in response to list of words

# Build the bigram and trigram models
bigram = gensim.models.Phrases(data_words, min_count=5, threshold=100) # higher threshold fewer phrases.
trigram = gensim.models.Phrases(bigram[data_words], threshold=100)
# Faster way to get a sentence clubbed as a trigram/bigram
bigram_mod = gensim.models.phrases.Phraser(bigram)
trigram_mod = gensim.models.phrases.Phraser(trigram)

data_words_nostops = remove_stopwords(data_words) # remove stop words

# Form Bigrams
data_words_bigrams = make_bigrams(data_words_nostops)

# Initialize spacy 'en' model, keeping only tagger component (for efficiency)
nlp = spacy.load("en_core_web_sm", disable=['parser', 'ner'])

# Do lemmatization keeping only noun, adj, vb, adv
data_lemmatized = lemmatization(data_words_bigrams, allowed_postags=['NOUN', 'ADJ', 'VERB', 'ADV'])

2022-12-21 09:26:18,726 | INFO | phrases.py:497 | learn_vocab | collecting all words and their counts
2022-12-21 09:26:18,727 | INFO | phrases.py:502 | learn_vocab | PROGRESS: at sentence #0, processed 0 words and 0 word types
2022-12-21 09:26:18,729 | INFO | phrases.py:525 | learn_vocab | collected 1065 word types from a corpus of 885 words (unigram + bigrams) and 107 sentences
2022-12-21 09:26:18,730 | INFO | phrases.py:580 | add_vocab | using 1065 counts as vocab in Phrases<0 vocab, min_count=5, threshold=100, max_vocab_size=40000000>
2022-12-21 09:26:18,731 | INFO | phrases.py:497 | learn_vocab | collecting all words and their counts
2022-12-21 09:26:18,732 | INFO | phrases.py:502 | learn_vocab | PROGRESS: at sentence #0, processed 0 words and 0 word types
2022-12-21 09:26:18,737 | INFO | phrases.py:525 | learn_vocab | collected 1065 word types from a corpus of 885 words (unigram + bigrams) and 107 sentences
2022-12-21 09:26:18,738 | INFO | phrases.py:580 | add_vocab | using 1065 counts as vocab in Phrases<0 vocab, min_count=5, threshold=100, max_vocab_size=40000000>
2022-12-21 09:26:18,739 | INFO | phrases.py:838 | __init__ | source_vocab length 1065
2022-12-21 09:26:18,746 | INFO | phrases.py:847 | __init__ | Phraser built with 0 phrasegrams
2022-12-21 09:26:18,747 | INFO | phrases.py:838 | __init__ | source_vocab length 1065
2022-12-21 09:26:18,755 | INFO | phrases.py:847 | __init__ | Phraser built with 0 phrasegrams

> 2) Create a corpus

In [12]:
import gensim.corpora as corpora

def prepare_corpus(doc_clean):
    """
    Input  : clean document
    Purpose: create term dictionary of our courpus and Converting list of documents (corpus) into Document Term Matrix
    Output : term dictionary and Document Term Matrix
    """
    # Creating the term dictionary of our courpus, where every unique term is assigned an index. dictionary = corpora.Dictionary(doc_clean)
    dictionary = corpora.Dictionary(doc_clean)
    # Converting list of documents (corpus) into Document Term Matrix using dictionary prepared above.
    doc_term_matrix = [dictionary.doc2bow(doc) for doc in doc_clean]
    # generate LDA model
    return dictionary,doc_term_matrix

In [13]:
import gensim.corpora as corpora
# Create Dictionary
id2word = corpora.Dictionary(data_lemmatized)
# Create Corpus
texts = data_lemmatized
# Term Document Frequency
corpus = [id2word.doc2bow(text) for text in texts]

2022-12-21 09:26:19,598 | INFO | dictionary.py:209 | add_documents | adding document #0 to Dictionary(0 unique tokens: [])
2022-12-21 09:26:19,600 | INFO | dictionary.py:214 | add_documents | built Dictionary(226 unique tokens: ['agent', 'attitude', 'belt', 'former', 'reason']...) from 107 documents (total 408 corpus positions)

> 3) LDA Model

In [14]:
from pprint import pprint

In [15]:
# number of topics
num_topics = 10

# Build LDA model
lda_model = gensim.models.LdaMulticore(corpus=corpus,
                                       id2word=id2word,
                                       num_topics=num_topics,
                                      random_state=3,
                                      chunksize=100,
                                       passes=10,
                                       per_word_topics=True)
# Print the Keyword in the 10 topics
pprint(lda_model.print_topics())
doc_lda = lda_model[corpus]

2022-12-21 09:26:19,608 | INFO | ldamodel.py:557 | init_dir_prior | using symmetric alpha at 0.1
2022-12-21 09:26:19,609 | INFO | ldamodel.py:557 | init_dir_prior | using symmetric eta at 0.1
2022-12-21 09:26:19,610 | INFO | ldamodel.py:481 | __init__ | using serial LDA version on this node
2022-12-21 09:26:19,611 | INFO | ldamulticore.py:238 | update | running online LDA training, 10 topics, 10 passes over the supplied corpus of 107 documents, updating every 700 documents, evaluating every ~107 documents, iterating 50x with a convergence threshold of 0.001000
2022-12-21 09:26:19,621 | INFO | ldamulticore.py:279 | update | training LDA model using 7 processes
2022-12-21 09:26:19,671 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 0, dispatched chunk #0 = documents up to #100/107, outstanding queue size 1
2022-12-21 09:26:19,677 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 0, dispatched chunk #1 = documents up to #107/107, outstanding queue size 2
2022-12-21 09:26:21,898 | INFO | ldamodel.py:1171 | show_topics | topic #3 (0.100): 0.042*"company" + 0.037*"work" + 0.033*"good" + 0.024*"none" + 0.023*"employee" + 0.022*"back" + 0.022*"month" + 0.021*"take" + 0.021*"go" + 0.019*"already"
2022-12-21 09:26:21,898 | INFO | ldamodel.py:1171 | show_topics | topic #9 (0.100): 0.286*"none" + 0.020*"take" + 0.020*"well" + 0.020*"resignation" + 0.020*"really" + 0.020*"family" + 0.020*"letter" + 0.020*"care" + 0.020*"salary" + 0.010*"company"
2022-12-21 09:26:21,899 | INFO | ldamodel.py:1171 | show_topics | topic #7 (0.100): 0.068*"salary" + 0.046*"company" + 0.046*"basic" + 0.024*"enough" + 0.024*"family" + 0.024*"compare" + 0.024*"cavity" + 0.024*"generous" + 0.024*"problem" + 0.024*"see"
2022-12-21 09:26:21,900 | INFO | ldamodel.py:1171 | show_topics | topic #6 (0.100): 0.032*"environment" + 0.029*"side" + 0.029*"corporate" + 0.029*"establish" + 0.029*"management" + 0.029*"compensate" + 0.029*"empathic" + 0.029*"pasture" + 0.029*"benefit" + 0.029*"assign"
2022-12-21 09:26:21,900 | INFO | ldamodel.py:1171 | show_topics | topic #5 (0.100): 0.081*"none" + 0.050*"sale" + 0.026*"evaluation" + 0.026*"friendly" + 0.026*"application" + 0.026*"user" + 0.013*"salary" + 0.013*"month" + 0.013*"one" + 0.013*"apply"
2022-12-21 09:26:21,901 | INFO | ldamodel.py:1049 | do_mstep | topic diff=7.379778, rho=1.000000
2022-12-21 09:26:21,903 | INFO | ldamodel.py:822 | log_perplexity | -6.685 per-word bound, 102.9 perplexity estimate based on a held-out corpus of 7 documents with 14 words
2022-12-21 09:26:21,904 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 1, dispatched chunk #0 = documents up to #100/107, outstanding queue size 1
2022-12-21 09:26:21,905 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 1, dispatched chunk #1 = documents up to #107/107, outstanding queue size 2
2022-12-21 09:26:21,918 | INFO | ldamodel.py:1171 | show_topics | topic #9 (0.100): 0.346*"none" + 0.019*"well" + 0.019*"really" + 0.019*"resignation" + 0.019*"family" + 0.019*"letter" + 0.014*"take" + 0.014*"care" + 0.014*"salary" + 0.010*"plan"
2022-12-21 09:26:21,919 | INFO | ldamodel.py:1171 | show_topics | topic #8 (0.100): 0.038*"work" + 0.035*"feel" + 0.029*"salary" + 0.025*"risk" + 0.025*"public" + 0.025*"exposure" + 0.025*"travel" + 0.025*"consider" + 0.025*"malayo" + 0.025*"location"
2022-12-21 09:26:21,919 | INFO | ldamodel.py:1171 | show_topics | topic #2 (0.100): 0.028*"feel" + 0.028*"leave" + 0.028*"tl" + 0.028*"personal" + 0.028*"make" + 0.028*"change" + 0.028*"last" + 0.028*"supervisor" + 0.028*"former" + 0.015*"work"
2022-12-21 09:26:21,920 | INFO | ldamodel.py:1171 | show_topics | topic #5 (0.100): 0.052*"sale" + 0.044*"none" + 0.027*"evaluation" + 0.027*"friendly" + 0.027*"application" + 0.027*"user" + 0.014*"salary" + 0.014*"month" + 0.014*"one" + 0.014*"apply"
2022-12-21 09:26:21,921 | INFO | ldamodel.py:1171 | show_topics | topic #7 (0.100): 0.090*"salary" + 0.044*"company" + 0.044*"basic" + 0.035*"low" + 0.023*"problem" + 0.023*"enough" + 0.023*"family" + 0.023*"compare" + 0.023*"cavity" + 0.023*"generous"
2022-12-21 09:26:21,921 | INFO | ldamodel.py:1049 | do_mstep | topic diff=0.071983, rho=0.570730
2022-12-21 09:26:21,923 | INFO | ldamodel.py:822 | log_perplexity | -6.511 per-word bound, 91.2 perplexity estimate based on a held-out corpus of 7 documents with 14 words
2022-12-21 09:26:21,924 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 2, dispatched chunk #0 = documents up to #100/107, outstanding queue size 1
2022-12-21 09:26:21,925 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 2, dispatched chunk #1 = documents up to #107/107, outstanding queue size 2
2022-12-21 09:26:21,935 | INFO | ldamodel.py:1171 | show_topics | topic #1 (0.100): 0.038*"health" + 0.035*"none" + 0.020*"problem" + 0.020*"low" + 0.020*"arrangement" + 0.020*"time" + 0.020*"wfh" + 0.020*"go" + 0.020*"agent" + 0.020*"hire"
2022-12-21 09:26:21,936 | INFO | ldamodel.py:1171 | show_topics | topic #0 (0.100): 0.068*"take" + 0.052*"care" + 0.039*"need" + 0.036*"call" + 0.036*"home" + 0.032*"mother" + 0.021*"stay" + 0.020*"family" + 0.019*"time" + 0.019*"hard"
2022-12-21 09:26:21,937 | INFO | ldamodel.py:1171 | show_topics | topic #4 (0.100): 0.029*"due" + 0.029*"environment" + 0.029*"offer" + 0.029*"supervisor" + 0.029*"accept" + 0.029*"unhealthy" + 0.029*"site" + 0.029*"fulltime" + 0.029*"become" + 0.029*"satisfied"
2022-12-21 09:26:21,937 | INFO | ldamodel.py:1171 | show_topics | topic #5 (0.100): 0.053*"sale" + 0.030*"none" + 0.027*"evaluation" + 0.027*"friendly" + 0.027*"application" + 0.027*"user" + 0.014*"salary" + 0.014*"especially" + 0.014*"month" + 0.014*"one"
2022-12-21 09:26:21,938 | INFO | ldamodel.py:1171 | show_topics | topic #7 (0.100): 0.097*"salary" + 0.044*"company" + 0.044*"basic" + 0.039*"low" + 0.023*"problem" + 0.023*"enough" + 0.023*"family" + 0.023*"compare" + 0.023*"cavity" + 0.023*"generous"
2022-12-21 09:26:21,939 | INFO | ldamodel.py:1049 | do_mstep | topic diff=0.059773, rho=0.495682
2022-12-21 09:26:21,940 | INFO | ldamodel.py:822 | log_perplexity | -6.439 per-word bound, 86.8 perplexity estimate based on a held-out corpus of 7 documents with 14 words
2022-12-21 09:26:21,941 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 3, dispatched chunk #0 = documents up to #100/107, outstanding queue size 1
2022-12-21 09:26:21,942 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 3, dispatched chunk #1 = documents up to #107/107, outstanding queue size 2
2022-12-21 09:26:21,953 | INFO | ldamodel.py:1171 | show_topics | topic #6 (0.100): 0.032*"environment" + 0.031*"side" + 0.031*"corporate" + 0.031*"establish" + 0.031*"management" + 0.031*"compensate" + 0.031*"empathic" + 0.031*"pasture" + 0.031*"look" + 0.031*"assign"
2022-12-21 09:26:21,954 | INFO | ldamodel.py:1171 | show_topics | topic #9 (0.100): 0.391*"none" + 0.019*"well" + 0.019*"resignation" + 0.019*"letter" + 0.019*"really" + 0.017*"family" + 0.011*"salary" + 0.010*"good" + 0.010*"company" + 0.010*"plan"
2022-12-21 09:26:21,954 | INFO | ldamodel.py:1171 | show_topics | topic #2 (0.100): 0.028*"feel" + 0.028*"leave" + 0.028*"personal" + 0.028*"former" + 0.028*"make" + 0.028*"tl" + 0.028*"change" + 0.028*"last" + 0.028*"supervisor" + 0.015*"work"
2022-12-21 09:26:21,955 | INFO | ldamodel.py:1171 | show_topics | topic #1 (0.100): 0.038*"health" + 0.023*"none" + 0.020*"problem" + 0.020*"low" + 0.020*"arrangement" + 0.020*"wfh" + 0.020*"agent" + 0.020*"time" + 0.020*"go" + 0.020*"hire"
2022-12-21 09:26:21,955 | INFO | ldamodel.py:1171 | show_topics | topic #4 (0.100): 0.030*"due" + 0.030*"environment" + 0.030*"offer" + 0.030*"supervisor" + 0.030*"accept" + 0.030*"unhealthy" + 0.030*"site" + 0.030*"fulltime" + 0.030*"become" + 0.030*"problem"
2022-12-21 09:26:21,956 | INFO | ldamodel.py:1049 | do_mstep | topic diff=0.041140, rho=0.444116
2022-12-21 09:26:21,958 | INFO | ldamodel.py:822 | log_perplexity | -6.396 per-word bound, 84.2 perplexity estimate based on a held-out corpus of 7 documents with 14 words
2022-12-21 09:26:21,959 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 4, dispatched chunk #0 = documents up to #100/107, outstanding queue size 1
2022-12-21 09:26:21,960 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 4, dispatched chunk #1 = documents up to #107/107, outstanding queue size 2

2022-12-21 09:26:21,970 | INFO | ldamodel.py:1171 | show_topics | topic #8 (0.100): 0.040*"work" + 0.039*"feel" + 0.022*"salary" + 0.021*"risk" + 0.021*"public" + 0.021*"exposure" + 0.021*"travel" + 0.021*"consider" + 0.021*"malayo" + 0.021*"location"
2022-12-21 09:26:21,970 | INFO | ldamodel.py:1171 | show_topics | topic #6 (0.100): 0.032*"environment" + 0.032*"side" + 0.032*"corporate" + 0.032*"establish" + 0.032*"management" + 0.032*"empathic" + 0.032*"compensate" + 0.032*"pasture" + 0.032*"look" + 0.032*"assign"
2022-12-21 09:26:21,971 | INFO | ldamodel.py:1171 | show_topics | topic #0 (0.100): 0.076*"take" + 0.060*"care" + 0.045*"need" + 0.034*"call" + 0.034*"home" + 0.033*"mother" + 0.026*"stay" + 0.022*"family" + 0.018*"time" + 0.018*"find"
2022-12-21 09:26:21,972 | INFO | ldamodel.py:1171 | show_topics | topic #5 (0.100): 0.054*"sale" + 0.028*"evaluation" + 0.028*"friendly" + 0.028*"application" + 0.028*"user" + 0.020*"none" + 0.014*"also" + 0.014*"especially" + 0.014*"ask" + 0.014*"already"
2022-12-21 09:26:21,972 | INFO | ldamodel.py:1171 | show_topics | topic #4 (0.100): 0.030*"due" + 0.030*"environment" + 0.030*"offer" + 0.030*"supervisor" + 0.030*"accept" + 0.030*"unhealthy" + 0.030*"site" + 0.030*"fulltime" + 0.030*"become" + 0.030*"problem"
2022-12-21 09:26:21,973 | INFO | ldamodel.py:1049 | do_mstep | topic diff=0.029976, rho=0.405887
2022-12-21 09:26:21,974 | INFO | ldamodel.py:822 | log_perplexity | -6.370 per-word bound, 82.7 perplexity estimate based on a held-out corpus of 7 documents with 14 words
2022-12-21 09:26:21,975 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 5, dispatched chunk #0 = documents up to #100/107, outstanding queue size 1
2022-12-21 09:26:21,976 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 5, dispatched chunk #1 = documents up to #107/107, outstanding queue size 2
2022-12-21 09:26:21,987 | INFO | ldamodel.py:1171 | show_topics | topic #5 (0.100): 0.054*"sale" + 0.028*"evaluation" + 0.028*"friendly" + 0.028*"application" + 0.028*"user" + 0.018*"none" + 0.014*"also" + 0.014*"especially" + 0.014*"ask" + 0.014*"already"
2022-12-21 09:26:21,988 | INFO | ldamodel.py:1171 | show_topics | topic #3 (0.100): 0.050*"work" + 0.038*"company" + 0.037*"go" + 0.037*"good" + 0.026*"take" + 0.025*"employee" + 0.025*"back" + 0.025*"month" + 0.025*"think" + 0.025*"setup"
2022-12-21 09:26:21,988 | INFO | ldamodel.py:1171 | show_topics | topic #4 (0.100): 0.030*"due" + 0.030*"environment" + 0.030*"offer" + 0.030*"accept" + 0.030*"unhealthy" + 0.030*"supervisor" + 0.030*"fulltime" + 0.030*"site" + 0.030*"problem" + 0.030*"become"
2022-12-21 09:26:21,989 | INFO | ldamodel.py:1171 | show_topics | topic #8 (0.100): 0.040*"work" + 0.040*"feel" + 0.022*"salary" + 0.021*"risk" + 0.021*"public" + 0.021*"exposure" + 0.021*"travel" + 0.021*"consider" + 0.021*"malayo" + 0.021*"location"
2022-12-21 09:26:21,989 | INFO | ldamodel.py:1171 | show_topics | topic #6 (0.100): 0.032*"environment" + 0.032*"establish" + 0.032*"side" + 0.032*"corporate" + 0.032*"management" + 0.032*"empathic" + 0.032*"compensate" + 0.032*"pasture" + 0.032*"look" + 0.032*"assign"
2022-12-21 09:26:21,990 | INFO | ldamodel.py:1049 | do_mstep | topic diff=0.022460, rho=0.376089
2022-12-21 09:26:21,992 | INFO | ldamodel.py:822 | log_perplexity | -6.355 per-word bound, 81.8 perplexity estimate based on a held-out corpus of 7 documents with 14 words
2022-12-21 09:26:21,992 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 6, dispatched chunk #0 = documents up to #100/107, outstanding queue size 1
2022-12-21 09:26:21,993 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 6, dispatched chunk #1 = documents up to #107/107, outstanding queue size 2
2022-12-21 09:26:22,004 | INFO | ldamodel.py:1171 | show_topics | topic #8 (0.100): 0.040*"work" + 0.040*"feel" + 0.021*"salary" + 0.021*"risk" + 0.021*"public" + 0.021*"travel" + 0.021*"exposure" + 0.021*"consider" + 0.021*"malayo" + 0.021*"location"
2022-12-21 09:26:22,004 | INFO | ldamodel.py:1171 | show_topics | topic #4 (0.100): 0.030*"due" + 0.030*"environment" + 0.030*"offer" + 0.030*"problem" + 0.030*"accept" + 0.030*"unhealthy" + 0.030*"supervisor" + 0.030*"fulltime" + 0.030*"site" + 0.030*"become"
2022-12-21 09:26:22,005 | INFO | ldamodel.py:1171 | show_topics | topic #9 (0.100): 0.412*"none" + 0.019*"resignation" + 0.019*"well" + 0.019*"letter" + 0.019*"really" + 0.015*"family" + 0.010*"good" + 0.010*"salary" + 0.010*"company" + 0.010*"send"
2022-12-21 09:26:22,005 | INFO | ldamodel.py:1171 | show_topics | topic #7 (0.100): 0.104*"salary" + 0.043*"company" + 0.043*"basic" + 0.043*"low" + 0.023*"problem" + 0.023*"enough" + 0.023*"family" + 0.023*"compare" + 0.023*"cavity" + 0.023*"generous"
2022-12-21 09:26:22,006 | INFO | ldamodel.py:1171 | show_topics | topic #6 (0.100): 0.032*"environment" + 0.032*"establish" + 0.032*"side" + 0.032*"corporate" + 0.032*"management" + 0.032*"empathic" + 0.032*"compensate" + 0.032*"pasture" + 0.032*"look" + 0.032*"assign"
2022-12-21 09:26:22,007 | INFO | ldamodel.py:1049 | do_mstep | topic diff=0.016953, rho=0.352017
2022-12-21 09:26:22,009 | INFO | ldamodel.py:822 | log_perplexity | -6.345 per-word bound, 81.3 perplexity estimate based on a held-out corpus of 7 documents with 14 words
2022-12-21 09:26:22,010 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 7, dispatched chunk #0 = documents up to #100/107, outstanding queue size 1
2022-12-21 09:26:22,011 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 7, dispatched chunk #1 = documents up to #107/107, outstanding queue size 2
2022-12-21 09:26:22,021 | INFO | ldamodel.py:1171 | show_topics | topic #4 (0.100): 0.030*"due" + 0.030*"environment" + 0.030*"problem" + 0.030*"offer" + 0.030*"accept" + 0.030*"unhealthy" + 0.030*"supervisor" + 0.030*"fulltime" + 0.030*"site" + 0.030*"become"
2022-12-21 09:26:22,021 | INFO | ldamodel.py:1171 | show_topics | topic #7 (0.100): 0.104*"salary" + 0.043*"company" + 0.043*"basic" + 0.043*"low" + 0.023*"problem" + 0.023*"enough" + 0.023*"family" + 0.023*"compare" + 0.023*"cavity" + 0.023*"generous"
2022-12-21 09:26:22,022 | INFO | ldamodel.py:1171 | show_topics | topic #9 (0.100): 0.414*"none" + 0.019*"well" + 0.019*"resignation" + 0.019*"letter" + 0.019*"really" + 0.015*"family" + 0.010*"good" + 0.010*"company" + 0.010*"salary" + 0.010*"send"
2022-12-21 09:26:22,022 | INFO | ldamodel.py:1171 | show_topics | topic #3 (0.100): 0.050*"work" + 0.038*"company" + 0.038*"go" + 0.037*"good" + 0.027*"take" + 0.026*"employee" + 0.026*"back" + 0.026*"month" + 0.026*"think" + 0.025*"setup"
2022-12-21 09:26:22,023 | INFO | ldamodel.py:1171 | show_topics | topic #0 (0.100): 0.079*"take" + 0.064*"care" + 0.048*"need" + 0.034*"call" + 0.034*"home" + 0.033*"mother" + 0.031*"stay" + 0.025*"family" + 0.018*"time" + 0.018*"find"
2022-12-21 09:26:22,023 | INFO | ldamodel.py:1049 | do_mstep | topic diff=0.012871, rho=0.332045
2022-12-21 09:26:22,026 | INFO | ldamodel.py:822 | log_perplexity | -6.339 per-word bound, 80.9 perplexity estimate based on a held-out corpus of 7 documents with 14 words
2022-12-21 09:26:22,026 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 8, dispatched chunk #0 = documents up to #100/107, outstanding queue size 1
2022-12-21 09:26:22,027 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 8, dispatched chunk #1 = documents up to #107/107, outstanding queue size 2
2022-12-21 09:26:22,038 | INFO | ldamodel.py:1171 | show_topics | topic #2 (0.100): 0.028*"feel" + 0.028*"leave" + 0.028*"personal" + 0.028*"former" + 0.028*"make" + 0.028*"tl" + 0.028*"change" + 0.028*"last" + 0.028*"supervisor" + 0.015*"work"
2022-12-21 09:26:22,038 | INFO | ldamodel.py:1171 | show_topics | topic #1 (0.100): 0.039*"health" + 0.020*"problem" + 0.020*"arrangement" + 0.020*"low" + 0.020*"agent" + 0.020*"wfh" + 0.020*"time" + 0.020*"hire" + 0.020*"delay" + 0.020*"onsite"
2022-12-21 09:26:22,039 | INFO | ldamodel.py:1171 | show_topics | topic #3 (0.100): 0.050*"work" + 0.038*"company" + 0.038*"go" + 0.037*"good" + 0.027*"take" + 0.026*"employee" + 0.026*"back" + 0.026*"month" + 0.026*"think" + 0.026*"setup"
2022-12-21 09:26:22,039 | INFO | ldamodel.py:1171 | show_topics | topic #4 (0.100): 0.030*"due" + 0.030*"problem" + 0.030*"environment" + 0.030*"offer" + 0.030*"accept" + 0.030*"unhealthy" + 0.030*"supervisor" + 0.030*"fulltime" + 0.030*"site" + 0.030*"become"

2022-12-21 09:26:22,040 | INFO | ldamodel.py:1171 | show_topics | topic #5 (0.100): 0.054*"sale" + 0.028*"evaluation" + 0.028*"friendly" + 0.028*"application" + 0.028*"user" + 0.015*"none" + 0.015*"also" + 0.015*"especially" + 0.015*"ask" + 0.015*"already"
2022-12-21 09:26:22,041 | INFO | ldamodel.py:1049 | do_mstep | topic diff=0.009829, rho=0.315127
2022-12-21 09:26:22,043 | INFO | ldamodel.py:822 | log_perplexity | -6.335 per-word bound, 80.7 perplexity estimate based on a held-out corpus of 7 documents with 14 words
2022-12-21 09:26:22,043 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 9, dispatched chunk #0 = documents up to #100/107, outstanding queue size 1
2022-12-21 09:26:22,045 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 9, dispatched chunk #1 = documents up to #107/107, outstanding queue size 2
2022-12-21 09:26:22,054 | INFO | ldamodel.py:1171 | show_topics | topic #4 (0.100): 0.030*"due" + 0.030*"problem" + 0.030*"environment" + 0.030*"offer" + 0.030*"accept" + 0.030*"unhealthy" + 0.030*"fulltime" + 0.030*"supervisor" + 0.030*"site" + 0.030*"become"
2022-12-21 09:26:22,055 | INFO | ldamodel.py:1171 | show_topics | topic #7 (0.100): 0.105*"salary" + 0.043*"company" + 0.043*"basic" + 0.043*"low" + 0.023*"problem" + 0.023*"enough" + 0.023*"family" + 0.023*"compare" + 0.023*"cavity" + 0.023*"generous"
2022-12-21 09:26:22,055 | INFO | ldamodel.py:1171 | show_topics | topic #5 (0.100): 0.054*"sale" + 0.028*"evaluation" + 0.028*"friendly" + 0.028*"application" + 0.028*"user" + 0.015*"none" + 0.015*"also" + 0.015*"especially" + 0.015*"ask" + 0.015*"already"
2022-12-21 09:26:22,056 | INFO | ldamodel.py:1171 | show_topics | topic #3 (0.100): 0.050*"work" + 0.038*"go" + 0.038*"company" + 0.037*"good" + 0.027*"take" + 0.026*"employee" + 0.026*"back" + 0.026*"month" + 0.026*"think" + 0.026*"setup"
2022-12-21 09:26:22,057 | INFO | ldamodel.py:1171 | show_topics | topic #0 (0.100): 0.079*"take" + 0.064*"care" + 0.049*"need" + 0.033*"call" + 0.033*"home" + 0.033*"mother" + 0.032*"stay" + 0.026*"family" + 0.018*"time" + 0.018*"find"
2022-12-21 09:26:22,057 | INFO | ldamodel.py:1049 | do_mstep | topic diff=0.007533, rho=0.300557
2022-12-21 09:26:22,059 | INFO | ldamodel.py:822 | log_perplexity | -6.333 per-word bound, 80.6 perplexity estimate based on a held-out corpus of 7 documents with 14 words
2022-12-21 09:26:22,095 | INFO | ldamodel.py:1171 | show_topics | topic #0 (0.100): 0.079*"take" + 0.064*"care" + 0.049*"need" + 0.033*"call" + 0.033*"home" + 0.033*"mother" + 0.032*"stay" + 0.026*"family" + 0.018*"time" + 0.018*"find"
2022-12-21 09:26:22,096 | INFO | ldamodel.py:1171 | show_topics | topic #1 (0.100): 0.039*"health" + 0.020*"problem" + 0.020*"arrangement" + 0.020*"low" + 0.020*"agent" + 0.020*"wfh" + 0.020*"time" + 0.020*"hire" + 0.020*"onsite" + 0.020*"delay"
2022-12-21 09:26:22,096 | INFO | ldamodel.py:1171 | show_topics | topic #2 (0.100): 0.028*"feel" + 0.028*"leave" + 0.028*"personal" + 0.028*"former" + 0.028*"make" + 0.028*"tl" + 0.028*"change" + 0.028*"last" + 0.028*"supervisor" + 0.015*"work"
2022-12-21 09:26:22,097 | INFO | ldamodel.py:1171 | show_topics | topic #3 (0.100): 0.050*"work" + 0.038*"go" + 0.038*"company" + 0.037*"good" + 0.027*"take" + 0.026*"employee" + 0.026*"back" + 0.026*"month" + 0.026*"think" + 0.026*"setup"
2022-12-21 09:26:22,098 | INFO | ldamodel.py:1171 | show_topics | topic #4 (0.100): 0.030*"due" + 0.030*"problem" + 0.030*"environment" + 0.030*"offer" + 0.030*"accept" + 0.030*"unhealthy" + 0.030*"fulltime" + 0.030*"supervisor" + 0.030*"site" + 0.030*"become"
2022-12-21 09:26:22,098 | INFO | ldamodel.py:1171 | show_topics | topic #5 (0.100): 0.054*"sale" + 0.028*"evaluation" + 0.028*"friendly" + 0.028*"application" + 0.028*"user" + 0.015*"none" + 0.015*"also" + 0.015*"especially" + 0.015*"ask" + 0.015*"already"
2022-12-21 09:26:22,099 | INFO | ldamodel.py:1171 | show_topics | topic #6 (0.100): 0.032*"environment" + 0.032*"establish" + 0.032*"corporate" + 0.032*"management" + 0.032*"side" + 0.032*"empathic" + 0.032*"compensate" + 0.032*"pasture" + 0.032*"assign" + 0.032*"look"
2022-12-21 09:26:22,100 | INFO | ldamodel.py:1171 | show_topics | topic #7 (0.100): 0.105*"salary" + 0.043*"company" + 0.043*"basic" + 0.043*"low" + 0.023*"problem" + 0.023*"enough" + 0.023*"family" + 0.023*"compare" + 0.023*"cavity" + 0.023*"generous"
2022-12-21 09:26:22,101 | INFO | ldamodel.py:1171 | show_topics | topic #8 (0.100): 0.040*"work" + 0.040*"feel" + 0.021*"salary" + 0.021*"risk" + 0.021*"public" + 0.021*"travel" + 0.021*"exposure" + 0.021*"consider" + 0.021*"malayo" + 0.021*"location"
2022-12-21 09:26:22,101 | INFO | ldamodel.py:1171 | show_topics | topic #9 (0.100): 0.417*"none" + 0.019*"resignation" + 0.019*"well" + 0.019*"letter" + 0.019*"really" + 0.014*"family" + 0.010*"good" + 0.010*"company" + 0.010*"salary" + 0.010*"send"

[(0,
  '0.079*"take" + 0.064*"care" + 0.049*"need" + 0.033*"call" + 0.033*"home" + '
  '0.033*"mother" + 0.032*"stay" + 0.026*"family" + 0.018*"time" + '
  '0.018*"find"'),
 (1,
  '0.039*"health" + 0.020*"problem" + 0.020*"arrangement" + 0.020*"low" + '
  '0.020*"agent" + 0.020*"wfh" + 0.020*"time" + 0.020*"hire" + 0.020*"onsite" '
  '+ 0.020*"delay"'),
 (2,
  '0.028*"feel" + 0.028*"leave" + 0.028*"personal" + 0.028*"former" + '
  '0.028*"make" + 0.028*"tl" + 0.028*"change" + 0.028*"last" + '
  '0.028*"supervisor" + 0.015*"work"'),
 (3,
  '0.050*"work" + 0.038*"go" + 0.038*"company" + 0.037*"good" + 0.027*"take" + '
  '0.026*"employee" + 0.026*"back" + 0.026*"month" + 0.026*"think" + '
  '0.026*"setup"'),
 (4,
  '0.030*"due" + 0.030*"problem" + 0.030*"environment" + 0.030*"offer" + '
  '0.030*"accept" + 0.030*"unhealthy" + 0.030*"fulltime" + 0.030*"supervisor" '
  '+ 0.030*"site" + 0.030*"become"'),
 (5,
  '0.054*"sale" + 0.028*"evaluation" + 0.028*"friendly" + 0.028*"application" '
  '+ 0.028*"user" + 0.015*"none" + 0.015*"also" + 0.015*"especially" + '
  '0.015*"ask" + 0.015*"already"'),
 (6,
  '0.032*"environment" + 0.032*"establish" + 0.032*"corporate" + '
  '0.032*"management" + 0.032*"side" + 0.032*"empathic" + 0.032*"compensate" + '
  '0.032*"pasture" + 0.032*"assign" + 0.032*"look"'),
 (7,
  '0.105*"salary" + 0.043*"company" + 0.043*"basic" + 0.043*"low" + '
  '0.023*"problem" + 0.023*"enough" + 0.023*"family" + 0.023*"compare" + '
  '0.023*"cavity" + 0.023*"generous"'),
 (8,
  '0.040*"work" + 0.040*"feel" + 0.021*"salary" + 0.021*"risk" + '
  '0.021*"public" + 0.021*"travel" + 0.021*"exposure" + 0.021*"consider" + '
  '0.021*"malayo" + 0.021*"location"'),
 (9,
  '0.417*"none" + 0.019*"resignation" + 0.019*"well" + 0.019*"letter" + '
  '0.019*"really" + 0.014*"family" + 0.010*"good" + 0.010*"company" + '
  '0.010*"salary" + 0.010*"send"')]

> 4) Select optimal number of topics

In [16]:
# supporting function
def compute_coherence_values(corpus, dictionary, k, a, b):
    
    lda_model = gensim.models.LdaMulticore(corpus=corpus,
                                           id2word=dictionary,
                                           num_topics=k, 
                                           random_state=100,
                                           chunksize=100,
                                           passes=10,
                                           alpha=a,
                                           eta=b)
    
    coherence_model_lda = CoherenceModel(model=lda_model, texts=data_lemmatized, dictionary=id2word, coherence='c_v')
    
    return coherence_model_lda.get_coherence()

In [17]:
# Baseline coherence score
from gensim.models import CoherenceModel
# Compute Coherence Score
coherence_model_lda = CoherenceModel(model=lda_model, texts=data_lemmatized, dictionary=id2word, coherence='c_v')
coherence_lda = coherence_model_lda.get_coherence()
print('\nBaseline Coherence Score: ', coherence_lda)

2022-12-21 09:26:22,118 | INFO | probability_estimation.py:155 | p_boolean_sliding_window | using ParallelWordOccurrenceAccumulator(processes=7, batch_size=64) to estimate probabilities from sliding windows
2022-12-21 09:26:23,888 | INFO | text_analysis.py:530 | terminate_workers | 7 accumulators retrieved from output queue
2022-12-21 09:26:23,918 | INFO | text_analysis.py:552 | merge_accumulators | accumulated word occurrence stats for 92 virtual documents

Baseline Coherence Score:  0.4133924412488167

In [18]:
# Optimize coherence score
import tqdm
grid = {}
grid['Validation_Set'] = {}
# Topics range
min_topics = 2
max_topics = 11
step_size = 1
topics_range = range(min_topics, max_topics, step_size)

# Alpha parameter
alpha = list(np.arange(0.01, 1, 0.3))
alpha.append('symmetric')
alpha.append('asymmetric')

# Beta parameter
beta = list(np.arange(0.01, 1, 0.3))
beta.append('symmetric')

# Validation sets
num_of_docs = len(corpus)
corpus_sets = [
#     gensim.utils.ClippedCorpus(corpus, int(num_of_docs*0.25)), 
#                gensim.utils.ClippedCorpus(corpus, int(num_of_docs*0.5)), 
               gensim.utils.ClippedCorpus(corpus, int(num_of_docs*0.75)), 
               corpus]

corpus_title = [
    #'25% Corpus','50% Corpus',
    '75% Corpus', '100% Corpus']

model_results = {'Validation_Set': [],
                 'Topics': [],
                 'Alpha': [],
                 'Beta': [],
                 'Coherence': []
                }

In [19]:
# # iterate through validation corpuses
# for i in tqdm_notebook(range(len(corpus_sets))):
#     # iterate through number of topics
#     for k in topics_range:
#         # iterate through alpha values
#         for a in alpha:
#             # iterare through beta values
#             for b in beta:
#                 # get the coherence score for the given parameters
#                 cv = compute_coherence_values(corpus=corpus_sets[i], dictionary=id2word, 
#                                               k=k, a=a, b=b)
#                 # Save the model results
#                 model_results['Validation_Set'].append(corpus_title[i])
#                 model_results['Topics'].append(k)
#                 model_results['Alpha'].append(a)
#                 model_results['Beta'].append(b)
#                 model_results['Coherence'].append(cv)

In [20]:
# # Create coherence dataframe
# coherence_results = (pd.DataFrame(model_results)
#                      .sort_values(by = 'Coherence')
#                     )

In [21]:
# # Plot results - find optimal alpha & beta to find best coherence, then reconfigure alpha & beta
# plot_df = (coherence_results
#              #.query("(Alpha != 'asymmetric') & (Alpha != 'symmetric') ", engine = 'python')
#              #.query("(Validation_Set != '25% Corpus') & (Validation_Set != '50% Corpus')", engine = 'python')
#              .query("(Alpha == 'symmetric') & (Beta == 'symmetric')", engine = 'python')
#              .sort_values(by = 'Topics', ascending = False)             
#             )
# plot_df

# # Plot
# plt.plot(plot_df['Topics'].to_list(), plot_df['Coherence'].to_list())
# plt.show()

In [22]:
# # Select optimal alpha & beta
# (coherence_results
#  .query("Topics == 6")
#  .sort_values(by = 'Coherence', ascending = False)
# )

> 5) Train final model with optimized hyperparameters

In [23]:
# Train final model
lda_model = gensim.models.LdaMulticore(corpus=corpus,
                                           id2word=id2word,
                                           num_topics=5, 
                                           random_state=3,
                                           chunksize=100,
                                           passes=10,
                                           alpha=0.61,
                                           eta='symmetric')

2022-12-21 09:26:24,298 | INFO | ldamodel.py:557 | init_dir_prior | using symmetric eta at 0.2
2022-12-21 09:26:24,299 | INFO | ldamodel.py:481 | __init__ | using serial LDA version on this node
2022-12-21 09:26:24,300 | INFO | ldamulticore.py:238 | update | running online LDA training, 5 topics, 10 passes over the supplied corpus of 107 documents, updating every 700 documents, evaluating every ~107 documents, iterating 50x with a convergence threshold of 0.001000
2022-12-21 09:26:24,302 | INFO | ldamulticore.py:279 | update | training LDA model using 7 processes
2022-12-21 09:26:24,353 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 0, dispatched chunk #0 = documents up to #100/107, outstanding queue size 1
2022-12-21 09:26:24,358 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 0, dispatched chunk #1 = documents up to #107/107, outstanding queue size 2
2022-12-21 09:26:26,210 | INFO | ldamodel.py:1171 | show_topics | topic #0 (0.610): 0.072*"none" + 0.020*"salary" + 0.019*"take" + 0.017*"work" + 0.014*"family" + 0.013*"care" + 0.013*"need" + 0.013*"feel" + 0.012*"home" + 0.012*"call"
2022-12-21 09:26:26,210 | INFO | ldamodel.py:1171 | show_topics | topic #1 (0.610): 0.086*"none" + 0.014*"salary" + 0.013*"problem" + 0.013*"feel" + 0.013*"leave" + 0.012*"go" + 0.011*"basic" + 0.011*"time" + 0.011*"health" + 0.010*"take"
2022-12-21 09:26:26,212 | INFO | ldamodel.py:1171 | show_topics | topic #2 (0.610): 0.069*"none" + 0.016*"salary" + 0.016*"work" + 0.013*"family" + 0.012*"company" + 0.012*"really" + 0.012*"low" + 0.011*"make" + 0.011*"feel" + 0.011*"leave"
2022-12-21 09:26:26,212 | INFO | ldamodel.py:1171 | show_topics | topic #3 (0.610): 0.076*"none" + 0.023*"work" + 0.018*"company" + 0.015*"good" + 0.015*"take" + 0.012*"sale" + 0.012*"leave" + 0.012*"month" + 0.011*"environment" + 0.011*"salary"
2022-12-21 09:26:26,213 | INFO | ldamodel.py:1171 | show_topics | topic #4 (0.610): 0.084*"none" + 0.024*"company" + 0.019*"salary" + 0.012*"family" + 0.012*"work" + 0.011*"compare" + 0.011*"really" + 0.010*"well" + 0.010*"problem" + 0.010*"take"
2022-12-21 09:26:26,214 | INFO | ldamodel.py:1049 | do_mstep | topic diff=1.457135, rho=1.000000
2022-12-21 09:26:26,218 | INFO | ldamodel.py:822 | log_perplexity | -6.940 per-word bound, 122.8 perplexity estimate based on a held-out corpus of 7 documents with 14 words
2022-12-21 09:26:26,219 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 1, dispatched chunk #0 = documents up to #100/107, outstanding queue size 1
2022-12-21 09:26:26,220 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 1, dispatched chunk #1 = documents up to #107/107, outstanding queue size 2
2022-12-21 09:26:26,241 | INFO | ldamodel.py:1171 | show_topics | topic #0 (0.610): 0.064*"none" + 0.027*"take" + 0.021*"care" + 0.018*"personal" + 0.017*"need" + 0.017*"home" + 0.017*"agent" + 0.017*"call" + 0.016*"work" + 0.016*"family"
2022-12-21 09:26:26,241 | INFO | ldamodel.py:1171 | show_topics | topic #1 (0.610): 0.096*"none" + 0.018*"problem" + 0.017*"feel" + 0.016*"salary" + 0.015*"basic" + 0.015*"wfh" + 0.014*"health" + 0.013*"go" + 0.012*"time" + 0.012*"leave"
2022-12-21 09:26:26,242 | INFO | ldamodel.py:1171 | show_topics | topic #2 (0.610): 0.066*"none" + 0.016*"leave" + 0.015*"tl" + 0.015*"low" + 0.015*"last" + 0.015*"change" + 0.014*"really" + 0.014*"try" + 0.014*"letter" + 0.014*"make"
2022-12-21 09:26:26,242 | INFO | ldamodel.py:1171 | show_topics | topic #3 (0.610): 0.072*"none" + 0.027*"work" + 0.021*"sale" + 0.020*"company" + 0.020*"good" + 0.016*"take" + 0.015*"environment" + 0.014*"month" + 0.014*"go" + 0.013*"think"
2022-12-21 09:26:26,243 | INFO | ldamodel.py:1171 | show_topics | topic #4 (0.610): 0.091*"none" + 0.028*"salary" + 0.025*"company" + 0.015*"family" + 0.014*"compare" + 0.014*"well" + 0.013*"really" + 0.013*"evaluation" + 0.013*"especially" + 0.011*"work"
2022-12-21 09:26:26,244 | INFO | ldamodel.py:1049 | do_mstep | topic diff=0.751511, rho=0.570730
2022-12-21 09:26:26,247 | INFO | ldamodel.py:822 | log_perplexity | -6.784 per-word bound, 110.2 perplexity estimate based on a held-out corpus of 7 documents with 14 words
2022-12-21 09:26:26,247 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 2, dispatched chunk #0 = documents up to #100/107, outstanding queue size 1
2022-12-21 09:26:26,249 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 2, dispatched chunk #1 = documents up to #107/107, outstanding queue size 2
2022-12-21 09:26:26,265 | INFO | ldamodel.py:1171 | show_topics | topic #0 (0.610): 0.053*"none" + 0.030*"take" + 0.024*"care" + 0.023*"personal" + 0.020*"need" + 0.019*"home" + 0.019*"agent" + 0.019*"call" + 0.018*"family" + 0.018*"former"
2022-12-21 09:26:26,266 | INFO | ldamodel.py:1171 | show_topics | topic #1 (0.610): 0.110*"none" + 0.023*"problem" + 0.019*"feel" + 0.018*"basic" + 0.018*"wfh" + 0.017*"salary" + 0.015*"health" + 0.013*"go" + 0.012*"offer" + 0.012*"time"
2022-12-21 09:26:26,266 | INFO | ldamodel.py:1171 | show_topics | topic #2 (0.610): 0.065*"none" + 0.019*"leave" + 0.018*"low" + 0.018*"tl" + 0.018*"last" + 0.018*"change" + 0.017*"try" + 0.017*"letter" + 0.016*"resignation" + 0.015*"really"
2022-12-21 09:26:26,267 | INFO | ldamodel.py:1171 | show_topics | topic #3 (0.610): 0.067*"none" + 0.029*"work" + 0.025*"sale" + 0.021*"good" + 0.021*"company" + 0.017*"environment" + 0.016*"take" + 0.016*"go" + 0.015*"month" + 0.014*"think"
2022-12-21 09:26:26,268 | INFO | ldamodel.py:1171 | show_topics | topic #4 (0.610): 0.097*"none" + 0.036*"salary" + 0.025*"company" + 0.016*"family" + 0.016*"compare" + 0.015*"well" + 0.015*"really" + 0.015*"evaluation" + 0.015*"especially" + 0.011*"work"
2022-12-21 09:26:26,268 | INFO | ldamodel.py:1049 | do_mstep | topic diff=0.496348, rho=0.495682
2022-12-21 09:26:26,272 | INFO | ldamodel.py:822 | log_perplexity | -6.548 per-word bound, 93.6 perplexity estimate based on a held-out corpus of 7 documents with 14 words
2022-12-21 09:26:26,272 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 3, dispatched chunk #0 = documents up to #100/107, outstanding queue size 1
2022-12-21 09:26:26,273 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 3, dispatched chunk #1 = documents up to #107/107, outstanding queue size 2
2022-12-21 09:26:26,288 | INFO | ldamodel.py:1171 | show_topics | topic #0 (0.610): 0.042*"none" + 0.032*"take" + 0.026*"care" + 0.025*"personal" + 0.021*"home" + 0.020*"need" + 0.020*"agent" + 0.020*"call" + 0.020*"former" + 0.019*"family"
2022-12-21 09:26:26,289 | INFO | ldamodel.py:1171 | show_topics | topic #1 (0.610): 0.129*"none" + 0.025*"problem" + 0.019*"feel" + 0.019*"basic" + 0.019*"wfh" + 0.017*"salary" + 0.014*"health" + 0.013*"offer" + 0.012*"arrangement" + 0.012*"go"
2022-12-21 09:26:26,289 | INFO | ldamodel.py:1171 | show_topics | topic #2 (0.610): 0.062*"none" + 0.021*"leave" + 0.020*"low" + 0.019*"tl" + 0.019*"last" + 0.019*"change" + 0.019*"try" + 0.019*"letter" + 0.019*"resignation" + 0.015*"really"
2022-12-21 09:26:26,290 | INFO | ldamodel.py:1171 | show_topics | topic #3 (0.610): 0.060*"none" + 0.030*"work" + 0.027*"sale" + 0.022*"good" + 0.021*"company" + 0.018*"go" + 0.017*"environment" + 0.016*"take" + 0.015*"month" + 0.015*"leave"
2022-12-21 09:26:26,291 | INFO | ldamodel.py:1171 | show_topics | topic #4 (0.610): 0.102*"none" + 0.041*"salary" + 0.025*"company" + 0.016*"really" + 0.016*"family" + 0.016*"compare" + 0.016*"well" + 0.016*"evaluation" + 0.016*"especially" + 0.011*"work"
2022-12-21 09:26:26,291 | INFO | ldamodel.py:1049 | do_mstep | topic diff=0.312963, rho=0.444116
2022-12-21 09:26:26,294 | INFO | ldamodel.py:822 | log_perplexity | -6.419 per-word bound, 85.6 perplexity estimate based on a held-out corpus of 7 documents with 14 words
2022-12-21 09:26:26,295 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 4, dispatched chunk #0 = documents up to #100/107, outstanding queue size 1
2022-12-21 09:26:26,296 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 4, dispatched chunk #1 = documents up to #107/107, outstanding queue size 2
2022-12-21 09:26:26,311 | INFO | ldamodel.py:1171 | show_topics | topic #0 (0.610): 0.033*"none" + 0.033*"take" + 0.027*"care" + 0.027*"personal" + 0.021*"home" + 0.021*"agent" + 0.021*"need" + 0.021*"call" + 0.021*"former" + 0.020*"family"

2022-12-21 09:26:26,311 | INFO | ldamodel.py:1171 | show_topics | topic #1 (0.610): 0.153*"none" + 0.027*"problem" + 0.019*"feel" + 0.019*"basic" + 0.019*"wfh" + 0.016*"salary" + 0.014*"health" + 0.012*"offer" + 0.012*"arrangement" + 0.011*"work"
2022-12-21 09:26:26,312 | INFO | ldamodel.py:1171 | show_topics | topic #2 (0.610): 0.057*"none" + 0.023*"low" + 0.022*"leave" + 0.020*"tl" + 0.020*"last" + 0.020*"change" + 0.020*"try" + 0.020*"letter" + 0.020*"resignation" + 0.015*"really"
2022-12-21 09:26:26,313 | INFO | ldamodel.py:1171 | show_topics | topic #3 (0.610): 0.053*"none" + 0.031*"work" + 0.028*"sale" + 0.022*"good" + 0.021*"company" + 0.020*"go" + 0.017*"environment" + 0.016*"take" + 0.015*"leave" + 0.015*"month"
2022-12-21 09:26:26,313 | INFO | ldamodel.py:1171 | show_topics | topic #4 (0.610): 0.103*"none" + 0.045*"salary" + 0.025*"company" + 0.017*"really" + 0.017*"family" + 0.016*"compare" + 0.016*"well" + 0.016*"evaluation" + 0.016*"especially" + 0.011*"work"
2022-12-21 09:26:26,314 | INFO | ldamodel.py:1049 | do_mstep | topic diff=0.198026, rho=0.405887
2022-12-21 09:26:26,316 | INFO | ldamodel.py:822 | log_perplexity | -6.353 per-word bound, 81.8 perplexity estimate based on a held-out corpus of 7 documents with 14 words
2022-12-21 09:26:26,317 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 5, dispatched chunk #0 = documents up to #100/107, outstanding queue size 1
2022-12-21 09:26:26,318 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 5, dispatched chunk #1 = documents up to #107/107, outstanding queue size 2
2022-12-21 09:26:26,333 | INFO | ldamodel.py:1171 | show_topics | topic #0 (0.610): 0.034*"take" + 0.028*"care" + 0.027*"personal" + 0.026*"none" + 0.021*"home" + 0.021*"agent" + 0.021*"need" + 0.021*"call" + 0.021*"former" + 0.021*"family"
2022-12-21 09:26:26,333 | INFO | ldamodel.py:1171 | show_topics | topic #1 (0.610): 0.182*"none" + 0.027*"problem" + 0.019*"wfh" + 0.019*"feel" + 0.019*"basic" + 0.015*"salary" + 0.013*"health" + 0.012*"offer" + 0.012*"arrangement" + 0.011*"work"
2022-12-21 09:26:26,334 | INFO | ldamodel.py:1171 | show_topics | topic #2 (0.610): 0.050*"none" + 0.025*"low" + 0.023*"leave" + 0.021*"tl" + 0.021*"last" + 0.021*"change" + 0.021*"try" + 0.021*"letter" + 0.021*"resignation" + 0.014*"really"
2022-12-21 09:26:26,335 | INFO | ldamodel.py:1171 | show_topics | topic #3 (0.610): 0.046*"none" + 0.032*"work" + 0.029*"sale" + 0.023*"good" + 0.022*"company" + 0.021*"go" + 0.017*"environment" + 0.016*"take" + 0.016*"leave" + 0.015*"month"
2022-12-21 09:26:26,335 | INFO | ldamodel.py:1171 | show_topics | topic #4 (0.610): 0.097*"none" + 0.048*"salary" + 0.025*"company" + 0.017*"really" + 0.017*"family" + 0.017*"compare" + 0.017*"well" + 0.017*"evaluation" + 0.016*"especially" + 0.012*"work"
2022-12-21 09:26:26,336 | INFO | ldamodel.py:1049 | do_mstep | topic diff=0.127935, rho=0.376089
2022-12-21 09:26:26,339 | INFO | ldamodel.py:822 | log_perplexity | -6.309 per-word bound, 79.3 perplexity estimate based on a held-out corpus of 7 documents with 14 words
2022-12-21 09:26:26,340 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 6, dispatched chunk #0 = documents up to #100/107, outstanding queue size 1
2022-12-21 09:26:26,341 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 6, dispatched chunk #1 = documents up to #107/107, outstanding queue size 2
2022-12-21 09:26:26,354 | INFO | ldamodel.py:1171 | show_topics | topic #0 (0.610): 0.034*"take" + 0.028*"care" + 0.028*"personal" + 0.022*"home" + 0.022*"agent" + 0.022*"need" + 0.022*"call" + 0.021*"former" + 0.021*"family" + 0.021*"supervisor"
2022-12-21 09:26:26,355 | INFO | ldamodel.py:1171 | show_topics | topic #1 (0.610): 0.211*"none" + 0.027*"problem" + 0.019*"wfh" + 0.019*"feel" + 0.018*"basic" + 0.014*"salary" + 0.012*"health" + 0.011*"offer" + 0.011*"arrangement" + 0.011*"work"
2022-12-21 09:26:26,355 | INFO | ldamodel.py:1171 | show_topics | topic #2 (0.610): 0.042*"none" + 0.028*"low" + 0.024*"leave" + 0.022*"tl" + 0.022*"last" + 0.022*"change" + 0.022*"try" + 0.021*"letter" + 0.021*"resignation" + 0.014*"really"
2022-12-21 09:26:26,356 | INFO | ldamodel.py:1171 | show_topics | topic #3 (0.610): 0.039*"none" + 0.032*"work" + 0.029*"sale" + 0.023*"good" + 0.023*"go" + 0.022*"company" + 0.017*"environment" + 0.017*"leave" + 0.016*"take" + 0.016*"back"
2022-12-21 09:26:26,356 | INFO | ldamodel.py:1171 | show_topics | topic #4 (0.610): 0.087*"none" + 0.052*"salary" + 0.026*"company" + 0.018*"really" + 0.017*"family" + 0.017*"compare" + 0.017*"well" + 0.017*"evaluation" + 0.017*"especially" + 0.012*"basic"
2022-12-21 09:26:26,357 | INFO | ldamodel.py:1049 | do_mstep | topic diff=0.085035, rho=0.352017
2022-12-21 09:26:26,359 | INFO | ldamodel.py:822 | log_perplexity | -6.272 per-word bound, 77.3 perplexity estimate based on a held-out corpus of 7 documents with 14 words
2022-12-21 09:26:26,360 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 7, dispatched chunk #0 = documents up to #100/107, outstanding queue size 1
2022-12-21 09:26:26,362 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 7, dispatched chunk #1 = documents up to #107/107, outstanding queue size 2
2022-12-21 09:26:26,374 | INFO | ldamodel.py:1171 | show_topics | topic #0 (0.610): 0.035*"take" + 0.029*"care" + 0.028*"personal" + 0.022*"home" + 0.022*"need" + 0.022*"agent" + 0.022*"call" + 0.022*"former" + 0.021*"family" + 0.021*"supervisor"
2022-12-21 09:26:26,375 | INFO | ldamodel.py:1171 | show_topics | topic #1 (0.610): 0.238*"none" + 0.026*"problem" + 0.018*"wfh" + 0.018*"feel" + 0.017*"basic" + 0.013*"salary" + 0.012*"health" + 0.011*"offer" + 0.011*"arrangement" + 0.011*"work"
2022-12-21 09:26:26,375 | INFO | ldamodel.py:1171 | show_topics | topic #2 (0.610): 0.035*"none" + 0.030*"low" + 0.025*"leave" + 0.022*"tl" + 0.022*"last" + 0.022*"change" + 0.022*"try" + 0.022*"letter" + 0.022*"resignation" + 0.014*"benefit"
2022-12-21 09:26:26,376 | INFO | ldamodel.py:1171 | show_topics | topic #3 (0.610): 0.033*"work" + 0.032*"none" + 0.030*"sale" + 0.024*"go" + 0.023*"good" + 0.022*"company" + 0.017*"leave" + 0.017*"environment" + 0.017*"take" + 0.016*"back"
2022-12-21 09:26:26,376 | INFO | ldamodel.py:1171 | show_topics | topic #4 (0.610): 0.077*"none" + 0.055*"salary" + 0.026*"company" + 0.018*"really" + 0.017*"family" + 0.017*"compare" + 0.017*"well" + 0.017*"evaluation" + 0.017*"especially" + 0.014*"basic"
2022-12-21 09:26:26,377 | INFO | ldamodel.py:1049 | do_mstep | topic diff=0.057912, rho=0.332045
2022-12-21 09:26:26,380 | INFO | ldamodel.py:822 | log_perplexity | -6.240 per-word bound, 75.6 perplexity estimate based on a held-out corpus of 7 documents with 14 words
2022-12-21 09:26:26,381 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 8, dispatched chunk #0 = documents up to #100/107, outstanding queue size 1
2022-12-21 09:26:26,382 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 8, dispatched chunk #1 = documents up to #107/107, outstanding queue size 2
2022-12-21 09:26:26,395 | INFO | ldamodel.py:1171 | show_topics | topic #0 (0.610): 0.035*"take" + 0.029*"care" + 0.029*"personal" + 0.022*"need" + 0.022*"home" + 0.022*"agent" + 0.022*"call" + 0.022*"former" + 0.021*"family" + 0.021*"supervisor"
2022-12-21 09:26:26,396 | INFO | ldamodel.py:1171 | show_topics | topic #1 (0.610): 0.260*"none" + 0.026*"problem" + 0.018*"wfh" + 0.018*"feel" + 0.015*"basic" + 0.012*"salary" + 0.011*"health" + 0.011*"offer" + 0.011*"arrangement" + 0.010*"work"
2022-12-21 09:26:26,396 | INFO | ldamodel.py:1171 | show_topics | topic #2 (0.610): 0.031*"low" + 0.029*"none" + 0.025*"leave" + 0.022*"tl" + 0.022*"last" + 0.022*"change" + 0.022*"try" + 0.022*"letter" + 0.022*"resignation" + 0.015*"benefit"
2022-12-21 09:26:26,397 | INFO | ldamodel.py:1171 | show_topics | topic #3 (0.610): 0.033*"work" + 0.030*"sale" + 0.026*"none" + 0.025*"go" + 0.023*"good" + 0.022*"company" + 0.018*"leave" + 0.017*"environment" + 0.017*"take" + 0.016*"back"
2022-12-21 09:26:26,397 | INFO | ldamodel.py:1171 | show_topics | topic #4 (0.610): 0.066*"none" + 0.057*"salary" + 0.026*"company" + 0.018*"really" + 0.018*"family" + 0.017*"compare" + 0.017*"well" + 0.017*"evaluation" + 0.017*"especially" + 0.015*"basic"

2022-12-21 09:26:26,398 | INFO | ldamodel.py:1049 | do_mstep | topic diff=0.040411, rho=0.315127
2022-12-21 09:26:26,400 | INFO | ldamodel.py:822 | log_perplexity | -6.212 per-word bound, 74.1 perplexity estimate based on a held-out corpus of 7 documents with 14 words
2022-12-21 09:26:26,401 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 9, dispatched chunk #0 = documents up to #100/107, outstanding queue size 1
2022-12-21 09:26:26,402 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 9, dispatched chunk #1 = documents up to #107/107, outstanding queue size 2
2022-12-21 09:26:26,414 | INFO | ldamodel.py:1171 | show_topics | topic #0 (0.610): 0.035*"take" + 0.029*"care" + 0.029*"personal" + 0.022*"need" + 0.022*"home" + 0.022*"agent" + 0.022*"call" + 0.022*"former" + 0.022*"supervisor" + 0.021*"family"
2022-12-21 09:26:26,415 | INFO | ldamodel.py:1171 | show_topics | topic #1 (0.610): 0.277*"none" + 0.026*"problem" + 0.018*"wfh" + 0.018*"feel" + 0.014*"basic" + 0.011*"salary" + 0.011*"health" + 0.010*"offer" + 0.010*"arrangement" + 0.010*"work"
2022-12-21 09:26:26,416 | INFO | ldamodel.py:1171 | show_topics | topic #2 (0.610): 0.033*"low" + 0.026*"leave" + 0.024*"none" + 0.022*"tl" + 0.022*"last" + 0.022*"change" + 0.022*"try" + 0.022*"letter" + 0.022*"resignation" + 0.015*"benefit"
2022-12-21 09:26:26,416 | INFO | ldamodel.py:1171 | show_topics | topic #3 (0.610): 0.033*"work" + 0.030*"sale" + 0.026*"go" + 0.023*"good" + 0.022*"company" + 0.022*"none" + 0.019*"leave" + 0.017*"environment" + 0.017*"take" + 0.016*"back"
2022-12-21 09:26:26,417 | INFO | ldamodel.py:1171 | show_topics | topic #4 (0.610): 0.060*"salary" + 0.058*"none" + 0.026*"company" + 0.018*"really" + 0.018*"family" + 0.017*"compare" + 0.017*"well" + 0.017*"evaluation" + 0.017*"especially" + 0.017*"basic"
2022-12-21 09:26:26,417 | INFO | ldamodel.py:1049 | do_mstep | topic diff=0.028903, rho=0.300557
2022-12-21 09:26:26,421 | INFO | ldamodel.py:822 | log_perplexity | -6.189 per-word bound, 73.0 perplexity estimate based on a held-out corpus of 7 documents with 14 words

> 4) Visualizing topics

For (1), you can manually select each topic to view its top most frequent and/or “relevant” terms, using different values of the λ parameter. This can help when you’re trying to assign a human interpretable name or “meaning” to each topic.

For (2), exploring the Intertopic Distance Plot can help you learn about how topics relate to each other, including potential higher-level structure between groups of topics.

**Interpretation:**


*Bar chart*
- Each bubble represents a topic. The larger the bubble, the higher percentage of the number of responses in the corpus is about that topic.
- Blue bars represent the overall frequency of each word in the corpus. If no topic is selected, the blue bars of the most frequently used words will be displayed.
- Red bars give the estimated number of times a given term was generated by a given topic. The word with the longest red bar is the word that is used the most by the responses belonging to that topic.
- <u>*Lambda*</u> -- Decreasing the lambda parameter, increases the weight of the ratio of the frequency of word given the topic / Overall frequency of the word in the documents. Important words for the given topic moves upward.
    - Lambda = 1, top words by frequency
    - Lambda = 0, top words by relevance to topic

*Bubble plot*
- The further the bubbles are away from each other, the more different they are. 
- The larger the bubble, the more frequent is the topic in the documents.
- Distance between the topics is an approximation of semantic relationship between the topics.
- The topic which shares common words will be overlapping (closer in distance) in comparison to the non-overlapping topic.
- A good topic model will have big and non-overlapping bubbles scattered throughout the chart. As we can see from the graph, the bubbles are clustered within one place.
- A topic model with a low number of topics will have big non-overlapping bubbles, scattered throughout the chart whereas, the topic model with a high number of topics, will have many overlapping small size bubbles, clustered in the chart.

In [24]:
import pyLDAvis.gensim
import pickle 
import pyLDAvis

In [25]:
# Visualize the topics
pyLDAvis.enable_notebook()
LDAvis_prepared = pyLDAvis.gensim.prepare(lda_model, corpus, id2word)
LDAvis_prepared = pyLDAvis.gensim.prepare(lda_model, corpus, id2word)
LDAvis_prepared

/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic
0      0.151109  0.058835       1        1  23.375336
3     -0.003276 -0.145732       2        1  23.008735
4     -0.073383  0.056603       3        1  20.516323
1     -0.104834  0.045370       4        1  16.944542
2      0.030383 -0.015076       5        1  16.155064, topic_info=        Term       Freq      Total Category  logprob  loglift
104     none  28.000000  28.000000  Default  30.0000  30.0000
30    salary   6.000000   6.000000  Default  29.0000  29.0000
19       low   3.000000   3.000000  Default  28.0000  28.0000
75      take   5.000000   5.000000  Default  27.0000  27.0000
189     sale   3.000000   3.000000  Default  26.0000  26.0000
..       ...        ...        ...      ...      ...      ...
55       ask   0.818570   1.989634   Topic5  -4.3885   0.9348
26    family   0.843469   4.628532   Topic5  -4.3586   0.1205
39      feel   0.818833   3.731863   Topic5  -4.3882   0.3062
4     reason   0.813934   2.640288   Topic5  -4.3942   0.6462
10   company   0.819405   5.877782   Topic5  -4.3875  -0.1474

[229 rows x 6 columns], token_table=      Topic      Freq      Term
term
32        5  0.759486  addition
106       1  0.507968    affect
106       3  0.507968    affect
0         1  0.760910     agent
8         2  0.396345   already
...     ...       ...       ...
80        3  0.153131      work
80        4  0.153131      work
138       2  0.759503    workno
97        4  0.839198     would
98        4  0.839139      zoom

[222 rows x 3 columns], R=30, lambda_step=0.01, plot_opts={'xlab': 'PC1', 'ylab': 'PC2'}, topic_order=[1, 4, 5, 2, 3])

# Post-modeling Exploratory Data Analysis

*Assign respondents to their topic clusters*

In [26]:
# Topic distribution for the whole document. Each element in the list is a pair of a topic’s id, and the probability that was assigned to it.
topic_dist = list(lda_model.get_document_topics(corpus))


# Classify responses to topics
cluster = []
probability = []

for i in range(0, len(topic_dist)):
    clust = [x for x,y in topic_dist[i]]
    prob = [y for x,y in topic_dist[i]]
    get_index = prob.index(max(prob))
    max_val = topic_dist[i][get_index]
    cluster.append(max_val[0])
    probability.append(max_val[1])
    
# Add classification to df
analysis_df['Topic'] = cluster
analysis_df['Topic_Probability'] = probability

/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [27]:
# Map topics to Oracle ID
id_topic_mapper = dict(zip(analysis_df['Oracle ID of former employee'], analysis_df['Topic']))
id_prob_mapper = dict(zip(analysis_df['Oracle ID of former employee'], analysis_df['Topic_Probability']))
id_rate_mapper = dict(zip(analysis_df['Oracle ID of former employee'], analysis_df['How would you rate your overall experience with TTEC on a scale of 1 to 5? 5 being Very Good and 1 being Not Good']))

# For those with missing Oracle ID, map to names
name_mapper = (analysis_df[~analysis_df.applymap(np.isreal)['Oracle ID of former employee']]
               .assign(Name = lambda x: x['Name of former employee'].apply(lambda x: x.upper()))
               [['Name','Topic']]
                
                     .set_index("Name").to_dict()['Topic']
)

name_mapper2 = (analysis_df[~analysis_df.applymap(np.isreal)['Oracle ID of former employee']]
               .assign(Name = lambda x: x['Name of former employee'].apply(lambda x: x.upper()))
               [['Name','Topic_Probability']]
                
                     .set_index("Name").to_dict()['Topic_Probability']
)

rating_mapper = (analysis_df[~analysis_df.applymap(np.isreal)['Oracle ID of former employee']]
               .assign(Name = lambda x: x['Name of former employee'].apply(lambda x: x.upper()))
               [['Name','How would you rate your overall experience with TTEC on a scale of 1 to 5? 5 being Very Good and 1 being Not Good']]
                
                     .set_index("Name").to_dict()['How would you rate your overall experience with TTEC on a scale of 1 to 5? 5 being Very Good and 1 being Not Good']
)

# Filter attrition df to contain respondents only
respondents_demog_df = (attrition_df
                         .assign(Topic1 = lambda x: x['EE Oracle Id'].map(id_topic_mapper),
                                 Prob1 = lambda x: x['EE Oracle Id'].map(id_prob_mapper),
                                 Rate1 = lambda x: x['EE Oracle Id'].map(id_rate_mapper),
                                 Name = lambda x: (x['First Name'] + " " + x['Last Name']).apply(lambda x: x.upper()),
                                 Topic = lambda x: np.where(x['Topic1'].isna(), x['Name'].map(name_mapper), x['Topic1']),
                                 Topic_Probability = lambda x: np.where(x['Prob1'].isna(), x['Name'].map(name_mapper2), x['Prob1']),
                                Rating = lambda x: np.where(x['Rate1'].isna(), x['Name'].map(rating_mapper), x['Rate1']),

                         )
                         .drop(['Topic1','Prob1','Rate1'], axis = 1)
                         .query("Topic.notna()", engine = 'python')
                         .sort_values(by = 'Topic')
                        )

/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

> 1) How many respondents belong to each topic cluster & what is the average probability score?

In [28]:
# "Number of Employees per Cluster & Average Probability Score")
gen_stats = (analysis_df
             .groupby(['Topic']).agg({'Oracle ID of former employee':'nunique', 'Topic_Probability':'describe'})
             .reset_index()
            )

gen_stats

print("Number of Employees per Cluster & Average Probability Score")

/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

  Topic Oracle ID of former employee Topic_Probability                      \
        Oracle ID of former employee             count      mean       std
0     0                           29              29.0  0.437508  0.262753
1     1                           50              50.0  0.412297  0.102538
2     2                            5               5.0  0.634117  0.247964
3     3                           13              13.0  0.636624  0.178088
4     4                           10              10.0  0.643820  0.201766


        min       25%       50%       75%       max
0  0.200000  0.200000  0.200000  0.698881  0.856930
1  0.378827  0.378846  0.378856  0.378867  0.879003
2  0.312896  0.512960  0.581255  0.845293  0.918182
3  0.342836  0.530142  0.629969  0.794119  0.893021
4  0.389035  0.430949  0.685374  0.819393  0.886861

Number of Employees per Cluster & Average Probability Score

> 2) Tenure, Topic Probability, and Employee Count by By Attrition Stage

In [29]:
(respondents_demog_df
 .groupby(['Topic','Stage Attrition']).agg({'EE Oracle Id':'nunique','Tenure In Months':['mean', 'std','median'],'Topic_Probability':['mean', 'std','median']})
 .unstack('Stage Attrition')
)

/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

                  EE Oracle Id            Tenure In Months             \
                       nunique                        mean
Stage Attrition Pre Production Production   Pre Production Production
Topic
0.0                        5.0       24.0         6.200000  21.833333
1.0                        6.0       44.0         5.833333  27.886364
2.0                        NaN        5.0              NaN  23.600000
3.0                        1.0       12.0         3.000000  28.083333
4.0                        2.0        8.0         3.000000  22.125000

                                                                     \
                           std                    median
Stage Attrition Pre Production Production Pre Production Production
Topic
0.0                   8.408329  18.767842            2.0       20.0
1.0                  11.839200  24.323609            1.0       20.0
2.0                        NaN  14.587666            NaN       19.0
3.0                        NaN  20.246025            3.0       22.5
4.0                   1.414214  19.931579            3.0       21.0

                Topic_Probability                                       \
                             mean                       std
Stage Attrition    Pre Production Production Pre Production Production
Topic
0.0                      0.509788   0.422450       0.287550   0.261334
1.0                      0.440821   0.408407       0.151785   0.095776
2.0                           NaN   0.634117            NaN   0.247964
3.0                      0.686918   0.632433            NaN   0.185336
4.0                      0.454394   0.691177       0.082717   0.196337


                        median
Stage Attrition Pre Production Production
Topic
0.0                   0.652950   0.200000
1.0                   0.378860   0.378854
2.0                        NaN   0.581255
3.0                   0.686918   0.613875
4.0                   0.454394   0.756475

> 3) Tenure, Topic Probability, and Employee Count by By Job Name

In [30]:
(respondents_demog_df
 .groupby(['Topic','Job Name','Stage Attrition']).agg({'EE Oracle Id':'nunique','Tenure In Months':['mean', 'std','median']})
 .unstack('Job Name')
)

/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

                      EE Oracle Id                                        \
                           nunique
Job Name                     CSR I CSR II CSR III Chat Sales Associate I
Topic Stage Attrition
0.0   Pre Production           2.0    3.0     NaN                    NaN
      Production               2.0   20.0     2.0                    NaN
1.0   Pre Production           1.0    5.0     NaN                    NaN
      Production               7.0   29.0     6.0                    NaN
2.0   Production               1.0    1.0     2.0                    NaN
3.0   Pre Production           1.0    NaN     NaN                    NaN
      Production               3.0    5.0     2.0                    1.0
4.0   Pre Production           2.0    NaN     NaN                    NaN
      Production               NaN    6.0     1.0                    NaN

                                          Tenure In Months                     \
                                                      mean
Job Name              ISR I TSR I TSR III            CSR I     CSR II CSR III
Topic Stage Attrition
0.0   Pre Production    NaN   NaN     NaN         3.500000   8.000000     NaN
      Production        NaN   NaN     NaN        19.000000  20.950000    33.5
1.0   Pre Production    NaN   NaN     NaN         1.000000   6.800000     NaN
      Production        NaN   1.0     1.0        28.142857  27.034483    29.5
2.0   Production        NaN   NaN     1.0        49.000000  12.000000    20.0
3.0   Pre Production    NaN   NaN     NaN         3.000000        NaN     NaN
      Production        NaN   NaN     1.0        40.666667  22.200000    18.0
4.0   Pre Production    NaN   NaN     NaN         3.000000        NaN     NaN
      Production        1.0   NaN     NaN              NaN  19.333333     2.0

                                                                             \
                                                                        std
Job Name              Chat Sales Associate I ISR I TSR I TSR III      CSR I
Topic Stage Attrition
0.0   Pre Production                     NaN   NaN   NaN     NaN   2.121320
      Production                         NaN   NaN   NaN     NaN   2.828427
1.0   Pre Production                     NaN   NaN   NaN     NaN        NaN
      Production                         NaN   NaN  56.0    13.0  19.143568
2.0   Production                         NaN   NaN   NaN    17.0        NaN
3.0   Pre Production                     NaN   NaN   NaN     NaN        NaN
      Production                        40.0   NaN   NaN    28.0  23.501773
4.0   Pre Production                     NaN   NaN   NaN     NaN   1.414214
      Production                         NaN  59.0   NaN     NaN        NaN

                                                                          \

Job Name                  CSR II    CSR III Chat Sales Associate I ISR I
Topic Stage Attrition
0.0   Pre Production   11.269428        NaN                    NaN   NaN
      Production       20.100995  10.606602                    NaN   NaN
1.0   Pre Production   12.969194        NaN                    NaN   NaN
      Production       27.288777  16.379866                    NaN   NaN
2.0   Production             NaN   1.414214                    NaN   NaN
3.0   Pre Production         NaN        NaN                    NaN   NaN
      Production       24.509182   2.828427                    NaN   NaN
4.0   Pre Production         NaN        NaN                    NaN   NaN
      Production       13.923601        NaN                    NaN   NaN

                                                           \
                                    median
Job Name              TSR I TSR III  CSR I CSR II CSR III
Topic Stage Attrition
0.0   Pre Production    NaN     NaN    3.5    2.0     NaN
      Production        NaN     NaN   19.0   19.0    33.5
1.0   Pre Production    NaN     NaN    1.0    1.0     NaN
      Production        NaN     NaN   27.0   18.0    28.5
2.0   Production        NaN     NaN   49.0   12.0    20.0
3.0   Pre Production    NaN     NaN    3.0    NaN     NaN
      Production        NaN     NaN   41.0   22.0    18.0
4.0   Pre Production    NaN     NaN    3.0    NaN     NaN
      Production        NaN     NaN    NaN   21.0     2.0



Job Name              Chat Sales Associate I ISR I TSR I TSR III
Topic Stage Attrition
0.0   Pre Production                     NaN   NaN   NaN     NaN
      Production                         NaN   NaN   NaN     NaN
1.0   Pre Production                     NaN   NaN   NaN     NaN
      Production                         NaN   NaN  56.0    13.0
2.0   Production                         NaN   NaN   NaN    17.0
3.0   Pre Production                     NaN   NaN   NaN     NaN
      Production                        40.0   NaN   NaN    28.0
4.0   Pre Production                     NaN   NaN   NaN     NaN
      Production                         NaN  59.0   NaN     NaN

> 4) Tenure, Topic Probability, and Employee Count by By Job Name

In [31]:
(respondents_demog_df
 .groupby(['Topic','Stage Attrition']).agg({'Rating': ['mean', 'std','median']})
 .round(1)
)

/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

                      Rating
                        mean  std median
Topic Stage Attrition
0.0   Pre Production     3.8  1.0    3.5
      Production         4.3  0.7    4.0
1.0   Pre Production     4.4  0.9    5.0
      Production         4.3  0.8    4.0
2.0   Production         4.0  0.0    4.0
3.0   Pre Production     4.0  NaN    4.0
      Production         3.6  0.8    4.0
4.0   Pre Production     5.0  NaN    5.0
      Production         4.1  0.4    4.0