In [1]:
# importing relevant libraries
import pandas as pd
import numpy as np
import json
import os
from itertools import chain

# import boto3

from tqdm.notebook import tqdm_notebook
import time

import csv
import re

# display all rows & columns
#pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# show all outputs
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

# Disable warnings
import warnings
warnings.filterwarnings("ignore")

**Import data for analysis**

In [2]:
# Import data
attrition_list = 'Hopeliner Copy of Sample 2022 Attrition List.xlsx'
responses = 'TTEC Interviews (Responses).xlsx'

attrition_df = pd.read_excel(attrition_list)
response_df = pd.read_excel(responses)

**Pre-processing of Dataset**

In [3]:
# Strip column names
attrition_df.columns = [x.strip() for x in attrition_df.columns]
response_df.columns = [x.strip() for x in response_df.columns]

# Response df - pre-processing
response_df.rename(columns =  {'Read Call Opening: \nHi (First Name), thank you for making time for this short interview or chat with us. As shared in our (email/ SMS) exchange, my name is (Interviewer Name). I am from e-BI Solutions. We are working with TTEC to find ways to improve their employee experience so we are grateful that you made time for this.':'Read Call Opening',
                              'Confidentiality Notice and Consent:\nPlease note that we will treat our conversation with confidentiality and only disclose information to the extent you wish to share them with TTEC. Our goal is to help them improve the employee experience through an unbiased study and analysis of the data we gather. We will ask for your sign-off on the final notes we will include in the study. Do you agree and consent to this interview/ short chat? (Share option to record video/ audio/ transcript only)\n\n(Wait for response. Proceed with questions as appropriate)': 'Confidentiality Notice and Consent',
                              }, inplace = True)

cols = ['Stated Reason for Leaving TTEC', 'Other considerations for leaving', 'Top 3 Low lights and impact to them',
'Highlights of their stay with TTEC', 'Suggestions on redesigning the experience',
'What would make you consider returning or referring friends and family members to TTEC?',
'Any questions for e-BI or TTEC?']

for col in cols:
    response_df[col] = response_df[col].astype(str)
    
# Add a new column for all reasons for leaving
response_df['All Leaving Reasons'] = response_df['Stated Reason for Leaving TTEC'] + " " + response_df['Other considerations for leaving']

## Pre-processing Descriptive Data

In [4]:
# pip install gensim
# pip install nltk
# pip install matplotlib
# pip install advertools
# Run 'python -m nltk.downloader all' on ubuntu
# pip install typing-extensions --upgrade

In [5]:
#import modules
import nltk
import gensim
import advertools as adv
import matplotlib.pyplot
import os.path
from gensim import corpora
from gensim.models import LsiModel
from nltk.tokenize import RegexpTokenizer
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from gensim.models.coherencemodel import CoherenceModel
import matplotlib.pyplot as plt

# Latent Dirichlet Allocation (LDA) Topic Analysis Model

**Resources:**
- [Evaluate Topic Models: Latent Dirichlet Allocation (LDA)](https://towardsdatascience.com/evaluate-topic-model-in-python-latent-dirichlet-allocation-lda-7d57484bb5d0)

- [pyLDAvis: Topic Modelling Exploration Tool That Every NLP Data Scientist Should Know](https://neptune.ai/blog/pyldavis-topic-modelling-exploration-tool-that-every-nlp-data-scientist-should-know)

In [6]:
from gensim.utils import simple_preprocess
from nltk.corpus import stopwords

# Stop words
stop_words = stopwords.words('english') + list(adv.stopwords['tagalog'])

# Functions
def sent_to_words(sentences):
    for sentence in sentences:
        # deacc=True removes punctuations
        yield(gensim.utils.simple_preprocess(str(sentence), deacc=True))
        
def remove_stopwords(texts):
    return [[word for word in simple_preprocess(str(doc)) 
             if word not in stop_words] for doc in texts]

def preprocess_data_indiv(doc_set):
    """
    Input  : docuemnt list
    Purpose: preprocess text (tokenize, removing stopwords, and stemming)
    Output : preprocessed text
    """
    # initialize regex tokenizer
    tokenizer = RegexpTokenizer(r'\w+')
    # create English & Tagalog stop words list
    en_stop = set(stopwords.words('english') + list(adv.stopwords['tagalog']))
    # Create p_stemmer of class PorterStemmer
    p_stemmer = PorterStemmer()
    # list for tokenized documents in loop
    texts = []
    # loop through document list
    for i in doc_set:
        # clean and tokenize document string
        raw = i.lower()
        tokens = tokenizer.tokenize(raw)
        # remove stop words from tokens
        stopped_tokens = [i for i in tokens if not i in en_stop]
        # stem tokens
        #stemmed_tokens = [p_stemmer.stem(i) for i in stopped_tokens]
        # add tokens to list
        texts.append(stopped_tokens)
    return texts

In [7]:
# NLTK Stop words
# import nltk
# nltk.download('stopwords')
from nltk.corpus import stopwords
stop_words = stopwords.words('english') + list(adv.stopwords['tagalog'])
stop_words.extend(['from', 'subject', 're', 'edu', 'use','employee','ttec','resign'])
# Define functions for stopwords, bigrams, trigrams and lemmatization
def remove_stopwords(texts):
    return [[word for word in simple_preprocess(str(doc)) if word not in stop_words] for doc in texts]
def make_bigrams(texts):
    return [bigram_mod[doc] for doc in texts]
def make_trigrams(texts):
    return [trigram_mod[bigram_mod[doc]] for doc in texts]
def lemmatization(texts, allowed_postags=['NOUN', 'ADJ', 'VERB', 'ADV']):
    """https://spacy.io/api/annotation"""
    texts_out = []
    for sent in texts:
        doc = nlp(" ".join(sent)) 
        texts_out.append([token.lemma_ for token in doc if token.pos_ in allowed_postags])
    return texts_out

In [8]:
# Create a copy of the original response dataframe
analysis_df = response_df.copy()

> 1) Remove punctuations, digits and stop words from text

In [9]:
# Remove punctuations & digits
import re
from string import digits
remove_digits = str.maketrans('', '', digits) # remove digits

for col in cols:
    analysis_df[col] = analysis_df[col].apply(lambda x: re.sub(r'[^\w\s]', '', x).translate(remove_digits).strip().lower())

In [10]:
import spacy
# !python -m spacy download en_core_web_lg 
# !python -m spacy download en_core_web_sm

In [11]:
analysis_df.columns

Index(['Timestamp', 'Email Address', 'Read Call Opening',
       'Confidentiality Notice and Consent', 'Name of former employee',
       'Oracle ID of former employee', 'Last day with TTEC (Complete Date)',
       'Stated Reason for Leaving TTEC', 'Other considerations for leaving',
       'Top 3 Low lights and impact to them',
       'Highlights of their stay with TTEC',
       'Suggestions on redesigning the experience',
       'What would make you consider returning or referring friends and family members to TTEC?',
       'Any questions for e-BI or TTEC?',
       'Closing: Thank the person for the time and trust. Show - responses. End call.',
       'How would you rate your overall experience with TTEC on a scale of 1 to 5? 5 being Very Good and 1 being Not Good',
       'All Leaving Reasons'],
      dtype='object')

In [12]:
# Remove stop words
data = analysis_df['What would make you consider returning or referring friends and family members to TTEC?'].to_list() # field to analyse (MANUAL INPUT)
data_words = list(sent_to_words(data)) # convert words in response to list of words

# Build the bigram and trigram models
bigram = gensim.models.Phrases(data_words, min_count=5, threshold=100) # higher threshold fewer phrases.
trigram = gensim.models.Phrases(bigram[data_words], threshold=100)
# Faster way to get a sentence clubbed as a trigram/bigram
bigram_mod = gensim.models.phrases.Phraser(bigram)
trigram_mod = gensim.models.phrases.Phraser(trigram)

data_words_nostops = remove_stopwords(data_words) # remove stop words

# Form Bigrams
data_words_bigrams = make_bigrams(data_words_nostops)

# Initialize spacy 'en' model, keeping only tagger component (for efficiency)
nlp = spacy.load("en_core_web_sm", disable=['parser', 'ner'])

# Do lemmatization keeping only noun, adj, vb, adv
data_lemmatized = lemmatization(data_words_bigrams, allowed_postags=['NOUN', 'ADJ', 'VERB', 'ADV'])

2022-12-21 09:28:11,347 | INFO | phrases.py:497 | learn_vocab | collecting all words and their counts
2022-12-21 09:28:11,349 | INFO | phrases.py:502 | learn_vocab | PROGRESS: at sentence #0, processed 0 words and 0 word types
2022-12-21 09:28:11,352 | INFO | phrases.py:525 | learn_vocab | collected 1347 word types from a corpus of 1281 words (unigram + bigrams) and 107 sentences
2022-12-21 09:28:11,353 | INFO | phrases.py:580 | add_vocab | using 1347 counts as vocab in Phrases<0 vocab, min_count=5, threshold=100, max_vocab_size=40000000>
2022-12-21 09:28:11,355 | INFO | phrases.py:497 | learn_vocab | collecting all words and their counts
2022-12-21 09:28:11,356 | INFO | phrases.py:502 | learn_vocab | PROGRESS: at sentence #0, processed 0 words and 0 word types
2022-12-21 09:28:11,364 | INFO | phrases.py:525 | learn_vocab | collected 1347 word types from a corpus of 1281 words (unigram + bigrams) and 107 sentences
2022-12-21 09:28:11,365 | INFO | phrases.py:580 | add_vocab | using 1347 counts as vocab in Phrases<0 vocab, min_count=5, threshold=100, max_vocab_size=40000000>
2022-12-21 09:28:11,366 | INFO | phrases.py:838 | __init__ | source_vocab length 1347
2022-12-21 09:28:11,377 | INFO | phrases.py:847 | __init__ | Phraser built with 0 phrasegrams
2022-12-21 09:28:11,377 | INFO | phrases.py:838 | __init__ | source_vocab length 1347
2022-12-21 09:28:11,389 | INFO | phrases.py:847 | __init__ | Phraser built with 0 phrasegrams

> 2) Create a corpus

In [13]:
import gensim.corpora as corpora

def prepare_corpus(doc_clean):
    """
    Input  : clean document
    Purpose: create term dictionary of our courpus and Converting list of documents (corpus) into Document Term Matrix
    Output : term dictionary and Document Term Matrix
    """
    # Creating the term dictionary of our courpus, where every unique term is assigned an index. dictionary = corpora.Dictionary(doc_clean)
    dictionary = corpora.Dictionary(doc_clean)
    # Converting list of documents (corpus) into Document Term Matrix using dictionary prepared above.
    doc_term_matrix = [dictionary.doc2bow(doc) for doc in doc_clean]
    # generate LDA model
    return dictionary,doc_term_matrix

In [14]:
import gensim.corpora as corpora
# Create Dictionary
id2word = corpora.Dictionary(data_lemmatized)
# Create Corpus
texts = data_lemmatized
# Term Document Frequency
corpus = [id2word.doc2bow(text) for text in texts]

2022-12-21 09:28:12,308 | INFO | dictionary.py:209 | add_documents | adding document #0 to Dictionary(0 unique tokens: [])
2022-12-21 09:28:12,310 | INFO | dictionary.py:214 | add_documents | built Dictionary(257 unique tokens: ['apply', 'company', 'consider', 'former', 'may']...) from 107 documents (total 646 corpus positions)

> 3) LDA Model

In [15]:
from pprint import pprint

In [16]:
# number of topics
num_topics = 10

# Build LDA model
lda_model = gensim.models.LdaMulticore(corpus=corpus,
                                       id2word=id2word,
                                       num_topics=num_topics,
                                      random_state=3,
                                      chunksize=100,
                                       passes=10,
                                       per_word_topics=True)
# Print the Keyword in the 10 topics
pprint(lda_model.print_topics())
doc_lda = lda_model[corpus]

2022-12-21 09:28:12,319 | INFO | ldamodel.py:557 | init_dir_prior | using symmetric alpha at 0.1
2022-12-21 09:28:12,320 | INFO | ldamodel.py:557 | init_dir_prior | using symmetric eta at 0.1
2022-12-21 09:28:12,321 | INFO | ldamodel.py:481 | __init__ | using serial LDA version on this node
2022-12-21 09:28:12,322 | INFO | ldamulticore.py:238 | update | running online LDA training, 10 topics, 10 passes over the supplied corpus of 107 documents, updating every 700 documents, evaluating every ~107 documents, iterating 50x with a convergence threshold of 0.001000
2022-12-21 09:28:12,331 | INFO | ldamulticore.py:279 | update | training LDA model using 7 processes
2022-12-21 09:28:12,394 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 0, dispatched chunk #0 = documents up to #100/107, outstanding queue size 1
2022-12-21 09:28:12,402 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 0, dispatched chunk #1 = documents up to #107/107, outstanding queue size 2
2022-12-21 09:28:14,532 | INFO | ldamodel.py:1171 | show_topics | topic #4 (0.100): 0.036*"good" + 0.036*"environment" + 0.036*"working" + 0.036*"help" + 0.036*"person" + 0.036*"none" + 0.019*"compensation" + 0.019*"benefit" + 0.019*"employee" + 0.019*"experience"
2022-12-21 09:28:14,533 | INFO | ldamodel.py:1171 | show_topics | topic #0 (0.100): 0.047*"benefit" + 0.032*"good" + 0.032*"refer" + 0.032*"friendly" + 0.032*"friend" + 0.017*"process" + 0.017*"management" + 0.017*"even" + 0.017*"manage" + 0.017*"first"
2022-12-21 09:28:14,534 | INFO | ldamodel.py:1171 | show_topics | topic #9 (0.100): 0.108*"good" + 0.042*"experience" + 0.032*"company" + 0.026*"people" + 0.017*"team" + 0.017*"return" + 0.017*"gain" + 0.016*"want" + 0.016*"positive" + 0.015*"working"
2022-12-21 09:28:14,535 | INFO | ldamodel.py:1171 | show_topics | topic #3 (0.100): 0.059*"good" + 0.040*"friend" + 0.030*"company" + 0.020*"wfh" + 0.020*"salary" + 0.020*"work" + 0.020*"also" + 0.020*"account" + 0.020*"recommend" + 0.020*"people"
2022-12-21 09:28:14,535 | INFO | ldamodel.py:1171 | show_topics | topic #1 (0.100): 0.052*"offer" + 0.032*"account" + 0.032*"wfh" + 0.030*"refer" + 0.024*"company" + 0.022*"shift" + 0.022*"friend" + 0.022*"handle" + 0.022*"setup" + 0.015*"back"
2022-12-21 09:28:14,536 | INFO | ldamodel.py:1049 | do_mstep | topic diff=7.322126, rho=1.000000
2022-12-21 09:28:14,539 | INFO | ldamodel.py:822 | log_perplexity | -6.811 per-word bound, 112.3 perplexity estimate based on a held-out corpus of 7 documents with 28 words
2022-12-21 09:28:14,539 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 1, dispatched chunk #0 = documents up to #100/107, outstanding queue size 1
2022-12-21 09:28:14,540 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 1, dispatched chunk #1 = documents up to #107/107, outstanding queue size 2
2022-12-21 09:28:14,558 | INFO | ldamodel.py:1171 | show_topics | topic #8 (0.100): 0.062*"salary" + 0.051*"good" + 0.034*"give" + 0.034*"basic" + 0.023*"employee" + 0.023*"dispute" + 0.023*"company" + 0.023*"well" + 0.023*"compensation" + 0.018*"incentive"
2022-12-21 09:28:14,558 | INFO | ldamodel.py:1171 | show_topics | topic #2 (0.100): 0.055*"go" + 0.044*"back" + 0.027*"good" + 0.022*"company" + 0.022*"salary" + 0.022*"increase" + 0.022*"site" + 0.022*"schedule" + 0.022*"fit" + 0.022*"pay"
2022-12-21 09:28:14,559 | INFO | ldamodel.py:1171 | show_topics | topic #5 (0.100): 0.047*"position" + 0.037*"work" + 0.037*"shift" + 0.037*"salary" + 0.037*"return" + 0.019*"company" + 0.019*"apply" + 0.019*"former" + 0.019*"consider" + 0.019*"environment"
2022-12-21 09:28:14,560 | INFO | ldamodel.py:1171 | show_topics | topic #6 (0.100): 0.052*"company" + 0.052*"benefit" + 0.027*"good" + 0.021*"process" + 0.021*"career" + 0.021*"recommend" + 0.021*"working" + 0.021*"long" + 0.021*"environment" + 0.021*"high"
2022-12-21 09:28:14,560 | INFO | ldamodel.py:1171 | show_topics | topic #4 (0.100): 0.036*"good" + 0.036*"environment" + 0.036*"working" + 0.036*"help" + 0.036*"person" + 0.036*"none" + 0.019*"compensation" + 0.019*"benefit" + 0.019*"employee" + 0.019*"experience"
2022-12-21 09:28:14,561 | INFO | ldamodel.py:1049 | do_mstep | topic diff=0.057195, rho=0.570730
2022-12-21 09:28:14,563 | INFO | ldamodel.py:822 | log_perplexity | -6.744 per-word bound, 107.2 perplexity estimate based on a held-out corpus of 7 documents with 28 words
2022-12-21 09:28:14,564 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 2, dispatched chunk #0 = documents up to #100/107, outstanding queue size 1
2022-12-21 09:28:14,565 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 2, dispatched chunk #1 = documents up to #107/107, outstanding queue size 2
2022-12-21 09:28:14,580 | INFO | ldamodel.py:1171 | show_topics | topic #9 (0.100): 0.104*"good" + 0.041*"experience" + 0.030*"company" + 0.025*"people" + 0.017*"team" + 0.017*"return" + 0.017*"gain" + 0.017*"want" + 0.017*"positive" + 0.017*"working"
2022-12-21 09:28:14,581 | INFO | ldamodel.py:1171 | show_topics | topic #6 (0.100): 0.053*"company" + 0.052*"benefit" + 0.030*"good" + 0.022*"process" + 0.022*"recommend" + 0.022*"career" + 0.022*"high" + 0.022*"environment" + 0.022*"working" + 0.022*"long"
2022-12-21 09:28:14,581 | INFO | ldamodel.py:1171 | show_topics | topic #3 (0.100): 0.048*"good" + 0.043*"friend" + 0.024*"company" + 0.022*"account" + 0.022*"wfh" + 0.022*"work" + 0.022*"also" + 0.022*"recommend" + 0.022*"mother" + 0.017*"high"
2022-12-21 09:28:14,582 | INFO | ldamodel.py:1171 | show_topics | topic #8 (0.100): 0.063*"salary" + 0.053*"good" + 0.033*"basic" + 0.033*"give" + 0.028*"employee" + 0.028*"compensation" + 0.026*"high" + 0.023*"dispute" + 0.023*"well" + 0.023*"company"
2022-12-21 09:28:14,583 | INFO | ldamodel.py:1171 | show_topics | topic #2 (0.100): 0.056*"go" + 0.045*"back" + 0.025*"good" + 0.023*"company" + 0.023*"increase" + 0.023*"salary" + 0.023*"site" + 0.023*"schedule" + 0.023*"pay" + 0.023*"fit"
2022-12-21 09:28:14,583 | INFO | ldamodel.py:1049 | do_mstep | topic diff=0.044686, rho=0.495682
2022-12-21 09:28:14,586 | INFO | ldamodel.py:822 | log_perplexity | -6.706 per-word bound, 104.4 perplexity estimate based on a held-out corpus of 7 documents with 28 words
2022-12-21 09:28:14,586 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 3, dispatched chunk #0 = documents up to #100/107, outstanding queue size 1
2022-12-21 09:28:14,587 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 3, dispatched chunk #1 = documents up to #107/107, outstanding queue size 2
2022-12-21 09:28:14,603 | INFO | ldamodel.py:1171 | show_topics | topic #6 (0.100): 0.053*"company" + 0.053*"benefit" + 0.031*"good" + 0.022*"process" + 0.022*"recommend" + 0.022*"career" + 0.022*"environment" + 0.022*"working" + 0.022*"high" + 0.022*"long"
2022-12-21 09:28:14,603 | INFO | ldamodel.py:1171 | show_topics | topic #1 (0.100): 0.050*"account" + 0.048*"offer" + 0.035*"wfh" + 0.032*"refer" + 0.030*"handle" + 0.024*"setup" + 0.023*"company" + 0.022*"shift" + 0.022*"friend" + 0.012*"back"
2022-12-21 09:28:14,604 | INFO | ldamodel.py:1171 | show_topics | topic #9 (0.100): 0.104*"good" + 0.041*"experience" + 0.029*"company" + 0.025*"people" + 0.017*"team" + 0.017*"gain" + 0.017*"return" + 0.017*"want" + 0.017*"positive" + 0.017*"working"
2022-12-21 09:28:14,605 | INFO | ldamodel.py:1171 | show_topics | topic #0 (0.100): 0.047*"benefit" + 0.032*"friend" + 0.032*"friendly" + 0.032*"refer" + 0.032*"good" + 0.017*"process" + 0.017*"first" + 0.017*"management" + 0.017*"already" + 0.017*"come"
2022-12-21 09:28:14,605 | INFO | ldamodel.py:1171 | show_topics | topic #4 (0.100): 0.035*"good" + 0.035*"environment" + 0.035*"working" + 0.035*"help" + 0.035*"person" + 0.035*"none" + 0.030*"employee" + 0.030*"benefit" + 0.018*"compensation" + 0.018*"experience"
2022-12-21 09:28:14,606 | INFO | ldamodel.py:1049 | do_mstep | topic diff=0.031292, rho=0.444116
2022-12-21 09:28:14,609 | INFO | ldamodel.py:822 | log_perplexity | -6.683 per-word bound, 102.7 perplexity estimate based on a held-out corpus of 7 documents with 28 words
2022-12-21 09:28:14,609 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 4, dispatched chunk #0 = documents up to #100/107, outstanding queue size 1

2022-12-21 09:28:14,610 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 4, dispatched chunk #1 = documents up to #107/107, outstanding queue size 2
2022-12-21 09:28:14,624 | INFO | ldamodel.py:1171 | show_topics | topic #2 (0.100): 0.057*"go" + 0.046*"back" + 0.028*"pay" + 0.023*"company" + 0.023*"schedule" + 0.023*"site" + 0.023*"fit" + 0.023*"consider" + 0.022*"good" + 0.020*"salary"
2022-12-21 09:28:14,625 | INFO | ldamodel.py:1171 | show_topics | topic #9 (0.100): 0.103*"good" + 0.041*"experience" + 0.028*"company" + 0.025*"people" + 0.017*"team" + 0.017*"gain" + 0.017*"return" + 0.017*"want" + 0.017*"positive" + 0.017*"working"
2022-12-21 09:28:14,626 | INFO | ldamodel.py:1171 | show_topics | topic #8 (0.100): 0.064*"salary" + 0.053*"good" + 0.033*"basic" + 0.033*"give" + 0.031*"employee" + 0.031*"compensation" + 0.030*"high" + 0.022*"dispute" + 0.022*"well" + 0.022*"company"
2022-12-21 09:28:14,626 | INFO | ldamodel.py:1171 | show_topics | topic #5 (0.100): 0.053*"position" + 0.036*"work" + 0.036*"return" + 0.036*"shift" + 0.036*"salary" + 0.019*"apply" + 0.019*"former" + 0.019*"may" + 0.019*"day" + 0.019*"consider"
2022-12-21 09:28:14,627 | INFO | ldamodel.py:1171 | show_topics | topic #0 (0.100): 0.047*"benefit" + 0.032*"friend" + 0.032*"friendly" + 0.032*"refer" + 0.032*"good" + 0.017*"process" + 0.017*"first" + 0.017*"already" + 0.017*"management" + 0.017*"come"
2022-12-21 09:28:14,628 | INFO | ldamodel.py:1049 | do_mstep | topic diff=0.024723, rho=0.405887
2022-12-21 09:28:14,630 | INFO | ldamodel.py:822 | log_perplexity | -6.668 per-word bound, 101.7 perplexity estimate based on a held-out corpus of 7 documents with 28 words
2022-12-21 09:28:14,630 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 5, dispatched chunk #0 = documents up to #100/107, outstanding queue size 1
2022-12-21 09:28:14,631 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 5, dispatched chunk #1 = documents up to #107/107, outstanding queue size 2
2022-12-21 09:28:14,646 | INFO | ldamodel.py:1171 | show_topics | topic #5 (0.100): 0.053*"position" + 0.036*"return" + 0.036*"work" + 0.036*"shift" + 0.036*"salary" + 0.019*"apply" + 0.019*"former" + 0.019*"may" + 0.019*"day" + 0.019*"consider"
2022-12-21 09:28:14,647 | INFO | ldamodel.py:1171 | show_topics | topic #0 (0.100): 0.047*"benefit" + 0.032*"friend" + 0.032*"friendly" + 0.032*"refer" + 0.032*"good" + 0.017*"process" + 0.017*"first" + 0.017*"already" + 0.017*"come" + 0.017*"management"
2022-12-21 09:28:14,648 | INFO | ldamodel.py:1171 | show_topics | topic #4 (0.100): 0.035*"good" + 0.035*"environment" + 0.035*"working" + 0.035*"none" + 0.035*"help" + 0.035*"person" + 0.033*"employee" + 0.033*"benefit" + 0.018*"compensation" + 0.018*"experience"
2022-12-21 09:28:14,648 | INFO | ldamodel.py:1171 | show_topics | topic #2 (0.100): 0.058*"go" + 0.046*"back" + 0.031*"pay" + 0.024*"company" + 0.024*"schedule" + 0.024*"site" + 0.024*"fit" + 0.024*"consider" + 0.020*"good" + 0.019*"salary"
2022-12-21 09:28:14,649 | INFO | ldamodel.py:1171 | show_topics | topic #6 (0.100): 0.054*"company" + 0.054*"benefit" + 0.032*"good" + 0.022*"process" + 0.022*"recommend" + 0.022*"career" + 0.022*"environment" + 0.022*"working" + 0.022*"long" + 0.022*"high"
2022-12-21 09:28:14,650 | INFO | ldamodel.py:1049 | do_mstep | topic diff=0.018939, rho=0.376089
2022-12-21 09:28:14,652 | INFO | ldamodel.py:822 | log_perplexity | -6.660 per-word bound, 101.1 perplexity estimate based on a held-out corpus of 7 documents with 28 words
2022-12-21 09:28:14,653 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 6, dispatched chunk #0 = documents up to #100/107, outstanding queue size 1
2022-12-21 09:28:14,654 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 6, dispatched chunk #1 = documents up to #107/107, outstanding queue size 2
2022-12-21 09:28:14,669 | INFO | ldamodel.py:1171 | show_topics | topic #4 (0.100): 0.035*"good" + 0.035*"environment" + 0.035*"working" + 0.035*"none" + 0.035*"help" + 0.035*"person" + 0.034*"employee" + 0.034*"benefit" + 0.018*"compensation" + 0.018*"experience"
2022-12-21 09:28:14,670 | INFO | ldamodel.py:1171 | show_topics | topic #9 (0.100): 0.103*"good" + 0.041*"experience" + 0.028*"company" + 0.025*"people" + 0.017*"team" + 0.017*"gain" + 0.017*"return" + 0.017*"want" + 0.017*"positive" + 0.017*"working"
2022-12-21 09:28:14,671 | INFO | ldamodel.py:1171 | show_topics | topic #5 (0.100): 0.053*"position" + 0.036*"return" + 0.036*"work" + 0.036*"shift" + 0.036*"salary" + 0.019*"apply" + 0.019*"former" + 0.019*"may" + 0.019*"day" + 0.019*"consider"
2022-12-21 09:28:14,672 | INFO | ldamodel.py:1171 | show_topics | topic #3 (0.100): 0.045*"good" + 0.044*"friend" + 0.023*"company" + 0.023*"account" + 0.023*"work" + 0.023*"wfh" + 0.023*"also" + 0.023*"recommend" + 0.023*"mother" + 0.013*"compensation"
2022-12-21 09:28:14,673 | INFO | ldamodel.py:1171 | show_topics | topic #8 (0.100): 0.064*"salary" + 0.053*"good" + 0.036*"basic" + 0.035*"high" + 0.033*"give" + 0.032*"employee" + 0.032*"compensation" + 0.022*"dispute" + 0.022*"well" + 0.022*"company"
2022-12-21 09:28:14,673 | INFO | ldamodel.py:1049 | do_mstep | topic diff=0.016666, rho=0.352017
2022-12-21 09:28:14,676 | INFO | ldamodel.py:822 | log_perplexity | -6.652 per-word bound, 100.5 perplexity estimate based on a held-out corpus of 7 documents with 28 words
2022-12-21 09:28:14,676 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 7, dispatched chunk #0 = documents up to #100/107, outstanding queue size 1
2022-12-21 09:28:14,677 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 7, dispatched chunk #1 = documents up to #107/107, outstanding queue size 2
2022-12-21 09:28:14,692 | INFO | ldamodel.py:1171 | show_topics | topic #8 (0.100): 0.065*"salary" + 0.053*"good" + 0.041*"high" + 0.038*"basic" + 0.034*"compensation" + 0.032*"give" + 0.032*"employee" + 0.024*"well" + 0.022*"company" + 0.022*"dispute"
2022-12-21 09:28:14,693 | INFO | ldamodel.py:1171 | show_topics | topic #6 (0.100): 0.056*"company" + 0.056*"benefit" + 0.034*"good" + 0.023*"process" + 0.023*"recommend" + 0.023*"career" + 0.023*"environment" + 0.023*"working" + 0.023*"long" + 0.020*"compensation"
2022-12-21 09:28:14,693 | INFO | ldamodel.py:1171 | show_topics | topic #3 (0.100): 0.045*"friend" + 0.045*"good" + 0.023*"account" + 0.023*"work" + 0.023*"wfh" + 0.023*"also" + 0.023*"recommend" + 0.023*"mother" + 0.023*"company" + 0.013*"compensation"
2022-12-21 09:28:14,694 | INFO | ldamodel.py:1171 | show_topics | topic #2 (0.100): 0.058*"go" + 0.047*"back" + 0.040*"pay" + 0.024*"company" + 0.024*"schedule" + 0.024*"site" + 0.024*"fit" + 0.024*"consider" + 0.018*"good" + 0.016*"salary"
2022-12-21 09:28:14,694 | INFO | ldamodel.py:1171 | show_topics | topic #9 (0.100): 0.103*"good" + 0.041*"experience" + 0.028*"company" + 0.025*"people" + 0.017*"team" + 0.017*"gain" + 0.017*"return" + 0.017*"want" + 0.017*"positive" + 0.017*"working"
2022-12-21 09:28:14,695 | INFO | ldamodel.py:1049 | do_mstep | topic diff=0.015858, rho=0.332045
2022-12-21 09:28:14,697 | INFO | ldamodel.py:822 | log_perplexity | -6.646 per-word bound, 100.2 perplexity estimate based on a held-out corpus of 7 documents with 28 words
2022-12-21 09:28:14,698 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 8, dispatched chunk #0 = documents up to #100/107, outstanding queue size 1
2022-12-21 09:28:14,699 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 8, dispatched chunk #1 = documents up to #107/107, outstanding queue size 2
2022-12-21 09:28:14,714 | INFO | ldamodel.py:1171 | show_topics | topic #2 (0.100): 0.059*"go" + 0.047*"back" + 0.043*"pay" + 0.024*"company" + 0.024*"schedule" + 0.024*"site" + 0.024*"fit" + 0.024*"consider" + 0.017*"good" + 0.016*"salary"
2022-12-21 09:28:14,715 | INFO | ldamodel.py:1171 | show_topics | topic #3 (0.100): 0.045*"friend" + 0.044*"good" + 0.023*"account" + 0.023*"work" + 0.023*"wfh" + 0.023*"also" + 0.023*"recommend" + 0.023*"mother" + 0.022*"company" + 0.012*"compensation"
2022-12-21 09:28:14,715 | INFO | ldamodel.py:1171 | show_topics | topic #1 (0.100): 0.054*"account" + 0.047*"offer" + 0.036*"wfh" + 0.033*"refer" + 0.032*"handle" + 0.024*"setup" + 0.022*"company" + 0.022*"shift" + 0.022*"friend" + 0.012*"back"

2022-12-21 09:28:14,716 | INFO | ldamodel.py:1171 | show_topics | topic #7 (0.100): 0.088*"salary" + 0.063*"increase" + 0.053*"good" + 0.051*"setup" + 0.051*"wfh" + 0.050*"offer" + 0.043*"company" + 0.029*"management" + 0.023*"package" + 0.023*"people"
2022-12-21 09:28:14,716 | INFO | ldamodel.py:1171 | show_topics | topic #5 (0.100): 0.054*"position" + 0.036*"return" + 0.036*"work" + 0.036*"shift" + 0.036*"salary" + 0.019*"apply" + 0.019*"former" + 0.019*"may" + 0.019*"day" + 0.019*"consider"
2022-12-21 09:28:14,717 | INFO | ldamodel.py:1049 | do_mstep | topic diff=0.013262, rho=0.315127
2022-12-21 09:28:14,720 | INFO | ldamodel.py:822 | log_perplexity | -6.642 per-word bound, 99.9 perplexity estimate based on a held-out corpus of 7 documents with 28 words
2022-12-21 09:28:14,721 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 9, dispatched chunk #0 = documents up to #100/107, outstanding queue size 1
2022-12-21 09:28:14,722 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 9, dispatched chunk #1 = documents up to #107/107, outstanding queue size 2
2022-12-21 09:28:14,736 | INFO | ldamodel.py:1171 | show_topics | topic #5 (0.100): 0.054*"position" + 0.036*"return" + 0.036*"work" + 0.036*"shift" + 0.036*"salary" + 0.019*"apply" + 0.019*"former" + 0.019*"may" + 0.019*"day" + 0.019*"refer"
2022-12-21 09:28:14,737 | INFO | ldamodel.py:1171 | show_topics | topic #3 (0.100): 0.045*"friend" + 0.043*"good" + 0.023*"account" + 0.023*"work" + 0.023*"wfh" + 0.023*"also" + 0.023*"mother" + 0.023*"recommend" + 0.021*"company" + 0.012*"compensation"
2022-12-21 09:28:14,738 | INFO | ldamodel.py:1171 | show_topics | topic #2 (0.100): 0.059*"go" + 0.047*"back" + 0.044*"pay" + 0.024*"company" + 0.024*"schedule" + 0.024*"site" + 0.024*"fit" + 0.024*"consider" + 0.016*"good" + 0.015*"salary"
2022-12-21 09:28:14,739 | INFO | ldamodel.py:1171 | show_topics | topic #7 (0.100): 0.088*"salary" + 0.064*"increase" + 0.054*"good" + 0.051*"setup" + 0.050*"wfh" + 0.050*"offer" + 0.043*"company" + 0.029*"management" + 0.023*"package" + 0.023*"people"
2022-12-21 09:28:14,739 | INFO | ldamodel.py:1171 | show_topics | topic #0 (0.100): 0.047*"benefit" + 0.032*"friend" + 0.032*"friendly" + 0.032*"refer" + 0.032*"good" + 0.017*"process" + 0.017*"first" + 0.017*"already" + 0.017*"come" + 0.017*"training"
2022-12-21 09:28:14,740 | INFO | ldamodel.py:1049 | do_mstep | topic diff=0.010872, rho=0.300557
2022-12-21 09:28:14,742 | INFO | ldamodel.py:822 | log_perplexity | -6.639 per-word bound, 99.6 perplexity estimate based on a held-out corpus of 7 documents with 28 words
2022-12-21 09:28:14,775 | INFO | ldamodel.py:1171 | show_topics | topic #0 (0.100): 0.047*"benefit" + 0.032*"friend" + 0.032*"friendly" + 0.032*"refer" + 0.032*"good" + 0.017*"process" + 0.017*"first" + 0.017*"already" + 0.017*"come" + 0.017*"training"
2022-12-21 09:28:14,777 | INFO | ldamodel.py:1171 | show_topics | topic #1 (0.100): 0.054*"account" + 0.047*"offer" + 0.036*"wfh" + 0.033*"refer" + 0.033*"handle" + 0.024*"setup" + 0.022*"company" + 0.022*"shift" + 0.022*"friend" + 0.012*"back"
2022-12-21 09:28:14,777 | INFO | ldamodel.py:1171 | show_topics | topic #2 (0.100): 0.059*"go" + 0.047*"back" + 0.044*"pay" + 0.024*"company" + 0.024*"schedule" + 0.024*"site" + 0.024*"fit" + 0.024*"consider" + 0.016*"good" + 0.015*"salary"
2022-12-21 09:28:14,778 | INFO | ldamodel.py:1171 | show_topics | topic #3 (0.100): 0.045*"friend" + 0.043*"good" + 0.023*"account" + 0.023*"work" + 0.023*"wfh" + 0.023*"also" + 0.023*"mother" + 0.023*"recommend" + 0.021*"company" + 0.012*"compensation"
2022-12-21 09:28:14,779 | INFO | ldamodel.py:1171 | show_topics | topic #4 (0.100): 0.035*"good" + 0.035*"environment" + 0.035*"working" + 0.035*"none" + 0.035*"help" + 0.035*"person" + 0.034*"employee" + 0.034*"benefit" + 0.018*"compensation" + 0.018*"experience"
2022-12-21 09:28:14,779 | INFO | ldamodel.py:1171 | show_topics | topic #5 (0.100): 0.054*"position" + 0.036*"return" + 0.036*"work" + 0.036*"shift" + 0.036*"salary" + 0.019*"apply" + 0.019*"former" + 0.019*"may" + 0.019*"day" + 0.019*"refer"
2022-12-21 09:28:14,780 | INFO | ldamodel.py:1171 | show_topics | topic #6 (0.100): 0.057*"company" + 0.057*"benefit" + 0.034*"good" + 0.023*"process" + 0.023*"recommend" + 0.023*"career" + 0.023*"environment" + 0.023*"working" + 0.023*"long" + 0.017*"compensation"
2022-12-21 09:28:14,781 | INFO | ldamodel.py:1171 | show_topics | topic #7 (0.100): 0.088*"salary" + 0.064*"increase" + 0.054*"good" + 0.051*"setup" + 0.050*"wfh" + 0.050*"offer" + 0.043*"company" + 0.029*"management" + 0.023*"package" + 0.023*"people"
2022-12-21 09:28:14,781 | INFO | ldamodel.py:1171 | show_topics | topic #8 (0.100): 0.067*"salary" + 0.053*"good" + 0.049*"high" + 0.039*"basic" + 0.036*"compensation" + 0.031*"give" + 0.031*"employee" + 0.027*"well" + 0.023*"company" + 0.021*"dispute"
2022-12-21 09:28:14,782 | INFO | ldamodel.py:1171 | show_topics | topic #9 (0.100): 0.103*"good" + 0.041*"experience" + 0.028*"company" + 0.025*"people" + 0.017*"team" + 0.017*"gain" + 0.017*"return" + 0.017*"want" + 0.017*"positive" + 0.017*"working"

[(0,
  '0.047*"benefit" + 0.032*"friend" + 0.032*"friendly" + 0.032*"refer" + '
  '0.032*"good" + 0.017*"process" + 0.017*"first" + 0.017*"already" + '
  '0.017*"come" + 0.017*"training"'),
 (1,
  '0.054*"account" + 0.047*"offer" + 0.036*"wfh" + 0.033*"refer" + '
  '0.033*"handle" + 0.024*"setup" + 0.022*"company" + 0.022*"shift" + '
  '0.022*"friend" + 0.012*"back"'),
 (2,
  '0.059*"go" + 0.047*"back" + 0.044*"pay" + 0.024*"company" + '
  '0.024*"schedule" + 0.024*"site" + 0.024*"fit" + 0.024*"consider" + '
  '0.016*"good" + 0.015*"salary"'),
 (3,
  '0.045*"friend" + 0.043*"good" + 0.023*"account" + 0.023*"work" + '
  '0.023*"wfh" + 0.023*"also" + 0.023*"mother" + 0.023*"recommend" + '
  '0.021*"company" + 0.012*"compensation"'),
 (4,
  '0.035*"good" + 0.035*"environment" + 0.035*"working" + 0.035*"none" + '
  '0.035*"help" + 0.035*"person" + 0.034*"employee" + 0.034*"benefit" + '
  '0.018*"compensation" + 0.018*"experience"'),
 (5,
  '0.054*"position" + 0.036*"return" + 0.036*"work" + 0.036*"shift" + '
  '0.036*"salary" + 0.019*"apply" + 0.019*"former" + 0.019*"may" + 0.019*"day" '
  '+ 0.019*"refer"'),
 (6,
  '0.057*"company" + 0.057*"benefit" + 0.034*"good" + 0.023*"process" + '
  '0.023*"recommend" + 0.023*"career" + 0.023*"environment" + 0.023*"working" '
  '+ 0.023*"long" + 0.017*"compensation"'),
 (7,
  '0.088*"salary" + 0.064*"increase" + 0.054*"good" + 0.051*"setup" + '
  '0.050*"wfh" + 0.050*"offer" + 0.043*"company" + 0.029*"management" + '
  '0.023*"package" + 0.023*"people"'),
 (8,
  '0.067*"salary" + 0.053*"good" + 0.049*"high" + 0.039*"basic" + '
  '0.036*"compensation" + 0.031*"give" + 0.031*"employee" + 0.027*"well" + '
  '0.023*"company" + 0.021*"dispute"'),
 (9,
  '0.103*"good" + 0.041*"experience" + 0.028*"company" + 0.025*"people" + '
  '0.017*"team" + 0.017*"gain" + 0.017*"return" + 0.017*"want" + '
  '0.017*"positive" + 0.017*"working"')]

> 4) Select optimal number of topics

In [17]:
# supporting function
def compute_coherence_values(corpus, dictionary, k, a, b):
    
    lda_model = gensim.models.LdaMulticore(corpus=corpus,
                                           id2word=dictionary,
                                           num_topics=k, 
                                           random_state=100,
                                           chunksize=100,
                                           passes=10,
                                           alpha=a,
                                           eta=b)
    
    coherence_model_lda = CoherenceModel(model=lda_model, texts=data_lemmatized, dictionary=id2word, coherence='c_v')
    
    return coherence_model_lda.get_coherence()

In [18]:
# Baseline coherence score
from gensim.models import CoherenceModel
# Compute Coherence Score
coherence_model_lda = CoherenceModel(model=lda_model, texts=data_lemmatized, dictionary=id2word, coherence='c_v')
coherence_lda = coherence_model_lda.get_coherence()
print('\nBaseline Coherence Score: ', coherence_lda)

2022-12-21 09:28:14,799 | INFO | probability_estimation.py:155 | p_boolean_sliding_window | using ParallelWordOccurrenceAccumulator(processes=7, batch_size=64) to estimate probabilities from sliding windows
2022-12-21 09:28:17,310 | INFO | text_analysis.py:530 | terminate_workers | 7 accumulators retrieved from output queue
2022-12-21 09:28:17,359 | INFO | text_analysis.py:552 | merge_accumulators | accumulated word occurrence stats for 102 virtual documents

Baseline Coherence Score:  0.40127736699530026

In [19]:
# Optimize coherence score
import tqdm
grid = {}
grid['Validation_Set'] = {}
# Topics range
min_topics = 2
max_topics = 11
step_size = 1
topics_range = range(min_topics, max_topics, step_size)

# Alpha parameter
alpha = list(np.arange(0.01, 1, 0.3))
alpha.append('symmetric')
alpha.append('asymmetric')

# Beta parameter
beta = list(np.arange(0.01, 1, 0.3))
beta.append('symmetric')

# Validation sets
num_of_docs = len(corpus)
corpus_sets = [
#     gensim.utils.ClippedCorpus(corpus, int(num_of_docs*0.25)), 
#                gensim.utils.ClippedCorpus(corpus, int(num_of_docs*0.5)), 
               gensim.utils.ClippedCorpus(corpus, int(num_of_docs*0.75)), 
               corpus]

corpus_title = [
    #'25% Corpus','50% Corpus',
    '75% Corpus', '100% Corpus']

model_results = {'Validation_Set': [],
                 'Topics': [],
                 'Alpha': [],
                 'Beta': [],
                 'Coherence': []
                }

In [20]:
# # iterate through validation corpuses
# for i in tqdm_notebook(range(len(corpus_sets))):
#     # iterate through number of topics
#     for k in topics_range:
#         # iterate through alpha values
#         for a in alpha:
#             # iterare through beta values
#             for b in beta:
#                 # get the coherence score for the given parameters
#                 cv = compute_coherence_values(corpus=corpus_sets[i], dictionary=id2word, 
#                                               k=k, a=a, b=b)
#                 # Save the model results
#                 model_results['Validation_Set'].append(corpus_title[i])
#                 model_results['Topics'].append(k)
#                 model_results['Alpha'].append(a)
#                 model_results['Beta'].append(b)
#                 model_results['Coherence'].append(cv)

In [21]:
# # Create coherence dataframe
# coherence_results = (pd.DataFrame(model_results)
#                      .sort_values(by = 'Coherence')
#                     )

In [22]:
# # Plot results
# plot_df = (coherence_results
#              #.query("(Alpha != 'asymmetric') & (Alpha != 'symmetric') ", engine = 'python')
#              #.query("(Validation_Set != '25% Corpus') & (Validation_Set != '50% Corpus')", engine = 'python')
#              .query("(Alpha == 'symmetric') & (Beta == 'symmetric')", engine = 'python')
#              .sort_values(by = 'Topics', ascending = False)             
#             )
# plot_df

# # Plot
# plt.plot(plot_df['Topics'].to_list(), plot_df['Coherence'].to_list())
# plt.show()

In [23]:
# # Select optimal alpha & beta
# (coherence_results
#  .query("Topics == 4")
#  .sort_values(by = 'Coherence', ascending = False)
# )

> 5) Train final model with optimized hyperparameters

In [24]:
# Train final model
lda_model = gensim.models.LdaMulticore(corpus=corpus,
                                           id2word=id2word,
                                           num_topics=4, 
                                           random_state=3,
                                           chunksize=100,
                                           passes=10,
                                           alpha='asymmetric',
                                           eta=0.9099999999999999)

2022-12-21 09:28:17,747 | INFO | ldamodel.py:564 | init_dir_prior | using asymmetric alpha [0.38961035, 0.25974026, 0.19480518, 0.15584415]
2022-12-21 09:28:17,748 | INFO | ldamodel.py:481 | __init__ | using serial LDA version on this node
2022-12-21 09:28:17,749 | INFO | ldamulticore.py:238 | update | running online LDA training, 4 topics, 10 passes over the supplied corpus of 107 documents, updating every 700 documents, evaluating every ~107 documents, iterating 50x with a convergence threshold of 0.001000
2022-12-21 09:28:17,750 | INFO | ldamulticore.py:279 | update | training LDA model using 7 processes
2022-12-21 09:28:17,795 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 0, dispatched chunk #0 = documents up to #100/107, outstanding queue size 1
2022-12-21 09:28:17,800 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 0, dispatched chunk #1 = documents up to #107/107, outstanding queue size 2
2022-12-21 09:28:19,896 | INFO | ldamodel.py:1171 | show_topics | topic #0 (0.390): 0.030*"good" + 0.024*"company" + 0.021*"benefit" + 0.014*"refer" + 0.013*"salary" + 0.013*"friend" + 0.012*"compensation" + 0.011*"experience" + 0.011*"working" + 0.010*"people"
2022-12-21 09:28:19,897 | INFO | ldamodel.py:1171 | show_topics | topic #1 (0.260): 0.024*"offer" + 0.024*"wfh" + 0.021*"setup" + 0.017*"account" + 0.016*"salary" + 0.012*"employee" + 0.012*"company" + 0.011*"basic" + 0.010*"good" + 0.010*"shift"
2022-12-21 09:28:19,897 | INFO | ldamodel.py:1171 | show_topics | topic #2 (0.195): 0.043*"good" + 0.016*"salary" + 0.016*"increase" + 0.013*"environment" + 0.011*"experience" + 0.010*"working" + 0.010*"company" + 0.009*"schedule" + 0.009*"compensation" + 0.008*"gain"
2022-12-21 09:28:19,898 | INFO | ldamodel.py:1171 | show_topics | topic #3 (0.156): 0.023*"good" + 0.023*"salary" + 0.019*"company" + 0.015*"friend" + 0.013*"go" + 0.013*"work" + 0.011*"back" + 0.010*"recommend" + 0.010*"people" + 0.010*"wfh"
2022-12-21 09:28:19,898 | INFO | ldamodel.py:1049 | do_mstep | topic diff=0.627560, rho=1.000000
2022-12-21 09:28:19,903 | INFO | ldamodel.py:822 | log_perplexity | -5.964 per-word bound, 62.4 perplexity estimate based on a held-out corpus of 7 documents with 28 words
2022-12-21 09:28:19,904 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 1, dispatched chunk #0 = documents up to #100/107, outstanding queue size 1
2022-12-21 09:28:19,905 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 1, dispatched chunk #1 = documents up to #107/107, outstanding queue size 2
2022-12-21 09:28:19,938 | INFO | ldamodel.py:1171 | show_topics | topic #0 (0.390): 0.036*"good" + 0.027*"company" + 0.023*"benefit" + 0.015*"refer" + 0.014*"friend" + 0.014*"compensation" + 0.014*"salary" + 0.013*"people" + 0.011*"working" + 0.011*"employee"
2022-12-21 09:28:19,940 | INFO | ldamodel.py:1171 | show_topics | topic #1 (0.260): 0.026*"wfh" + 0.025*"offer" + 0.023*"setup" + 0.018*"account" + 0.017*"salary" + 0.011*"basic" + 0.011*"company" + 0.011*"employee" + 0.010*"shift" + 0.010*"handle"
2022-12-21 09:28:19,941 | INFO | ldamodel.py:1171 | show_topics | topic #2 (0.195): 0.041*"good" + 0.019*"increase" + 0.016*"salary" + 0.013*"experience" + 0.012*"environment" + 0.010*"gain" + 0.009*"working" + 0.009*"schedule" + 0.008*"basic" + 0.008*"pay"
2022-12-21 09:28:19,942 | INFO | ldamodel.py:1171 | show_topics | topic #3 (0.156): 0.022*"salary" + 0.019*"good" + 0.017*"company" + 0.014*"friend" + 0.013*"go" + 0.013*"work" + 0.011*"back" + 0.010*"wfh" + 0.010*"site" + 0.009*"recommend"
2022-12-21 09:28:19,943 | INFO | ldamodel.py:1049 | do_mstep | topic diff=0.053468, rho=0.570730
2022-12-21 09:28:19,948 | INFO | ldamodel.py:822 | log_perplexity | -5.938 per-word bound, 61.3 perplexity estimate based on a held-out corpus of 7 documents with 28 words
2022-12-21 09:28:19,949 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 2, dispatched chunk #0 = documents up to #100/107, outstanding queue size 1
2022-12-21 09:28:19,951 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 2, dispatched chunk #1 = documents up to #107/107, outstanding queue size 2
2022-12-21 09:28:19,983 | INFO | ldamodel.py:1171 | show_topics | topic #0 (0.390): 0.041*"good" + 0.030*"company" + 0.023*"benefit" + 0.016*"salary" + 0.016*"friend" + 0.015*"refer" + 0.015*"compensation" + 0.014*"people" + 0.012*"working" + 0.011*"employee"
2022-12-21 09:28:19,983 | INFO | ldamodel.py:1171 | show_topics | topic #1 (0.260): 0.028*"wfh" + 0.026*"offer" + 0.023*"setup" + 0.019*"account" + 0.017*"salary" + 0.012*"basic" + 0.010*"company" + 0.010*"employee" + 0.010*"shift" + 0.010*"handle"
2022-12-21 09:28:19,984 | INFO | ldamodel.py:1171 | show_topics | topic #2 (0.195): 0.040*"good" + 0.020*"increase" + 0.015*"salary" + 0.014*"experience" + 0.012*"environment" + 0.011*"gain" + 0.009*"working" + 0.009*"schedule" + 0.008*"pay" + 0.008*"basic"
2022-12-21 09:28:19,985 | INFO | ldamodel.py:1171 | show_topics | topic #3 (0.156): 0.020*"salary" + 0.015*"company" + 0.014*"good" + 0.014*"go" + 0.014*"work" + 0.013*"friend" + 0.011*"back" + 0.011*"wfh" + 0.011*"site" + 0.008*"also"
2022-12-21 09:28:19,986 | INFO | ldamodel.py:1049 | do_mstep | topic diff=0.036149, rho=0.495682
2022-12-21 09:28:19,991 | INFO | ldamodel.py:822 | log_perplexity | -5.932 per-word bound, 61.1 perplexity estimate based on a held-out corpus of 7 documents with 28 words
2022-12-21 09:28:19,991 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 3, dispatched chunk #0 = documents up to #100/107, outstanding queue size 1
2022-12-21 09:28:19,994 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 3, dispatched chunk #1 = documents up to #107/107, outstanding queue size 2
2022-12-21 09:28:20,029 | INFO | ldamodel.py:1171 | show_topics | topic #0 (0.390): 0.043*"good" + 0.032*"company" + 0.024*"benefit" + 0.018*"salary" + 0.016*"friend" + 0.015*"refer" + 0.015*"compensation" + 0.014*"people" + 0.012*"high" + 0.012*"working"
2022-12-21 09:28:20,030 | INFO | ldamodel.py:1171 | show_topics | topic #1 (0.260): 0.028*"wfh" + 0.026*"offer" + 0.024*"setup" + 0.019*"account" + 0.016*"salary" + 0.012*"basic" + 0.010*"employee" + 0.010*"company" + 0.010*"shift" + 0.010*"career"
2022-12-21 09:28:20,030 | INFO | ldamodel.py:1171 | show_topics | topic #2 (0.195): 0.040*"good" + 0.022*"increase" + 0.016*"salary" + 0.014*"experience" + 0.012*"environment" + 0.012*"gain" + 0.009*"schedule" + 0.009*"working" + 0.009*"pay" + 0.009*"annual"
2022-12-21 09:28:20,031 | INFO | ldamodel.py:1171 | show_topics | topic #3 (0.156): 0.016*"salary" + 0.014*"go" + 0.013*"work" + 0.013*"company" + 0.012*"friend" + 0.011*"back" + 0.011*"wfh" + 0.011*"site" + 0.011*"good" + 0.009*"also"
2022-12-21 09:28:20,032 | INFO | ldamodel.py:1049 | do_mstep | topic diff=0.025053, rho=0.444116
2022-12-21 09:28:20,035 | INFO | ldamodel.py:822 | log_perplexity | -5.932 per-word bound, 61.1 perplexity estimate based on a held-out corpus of 7 documents with 28 words
2022-12-21 09:28:20,035 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 4, dispatched chunk #0 = documents up to #100/107, outstanding queue size 1
2022-12-21 09:28:20,037 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 4, dispatched chunk #1 = documents up to #107/107, outstanding queue size 2
2022-12-21 09:28:20,065 | INFO | ldamodel.py:1171 | show_topics | topic #0 (0.390): 0.045*"good" + 0.034*"company" + 0.024*"benefit" + 0.020*"salary" + 0.017*"friend" + 0.015*"people" + 0.015*"compensation" + 0.015*"refer" + 0.013*"high" + 0.012*"employee"
2022-12-21 09:28:20,066 | INFO | ldamodel.py:1171 | show_topics | topic #1 (0.260): 0.029*"wfh" + 0.026*"offer" + 0.024*"setup" + 0.019*"account" + 0.015*"salary" + 0.011*"basic" + 0.010*"employee" + 0.010*"shift" + 0.010*"career" + 0.010*"handle"
2022-12-21 09:28:20,066 | INFO | ldamodel.py:1171 | show_topics | topic #2 (0.195): 0.039*"good" + 0.023*"increase" + 0.016*"salary" + 0.015*"experience" + 0.012*"environment" + 0.012*"gain" + 0.009*"schedule" + 0.009*"working" + 0.009*"annual" + 0.009*"pay"
2022-12-21 09:28:20,067 | INFO | ldamodel.py:1171 | show_topics | topic #3 (0.156): 0.014*"go" + 0.014*"salary" + 0.013*"work" + 0.012*"friend" + 0.012*"back" + 0.011*"site" + 0.011*"wfh" + 0.011*"company" + 0.009*"also" + 0.009*"consider"

2022-12-21 09:28:20,068 | INFO | ldamodel.py:1049 | do_mstep | topic diff=0.019929, rho=0.405887
2022-12-21 09:28:20,073 | INFO | ldamodel.py:822 | log_perplexity | -5.941 per-word bound, 61.4 perplexity estimate based on a held-out corpus of 7 documents with 28 words
2022-12-21 09:28:20,073 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 5, dispatched chunk #0 = documents up to #100/107, outstanding queue size 1
2022-12-21 09:28:20,075 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 5, dispatched chunk #1 = documents up to #107/107, outstanding queue size 2
2022-12-21 09:28:20,099 | INFO | ldamodel.py:1171 | show_topics | topic #0 (0.390): 0.046*"good" + 0.035*"company" + 0.024*"benefit" + 0.021*"salary" + 0.017*"friend" + 0.016*"people" + 0.015*"compensation" + 0.015*"refer" + 0.014*"high" + 0.012*"employee"
2022-12-21 09:28:20,100 | INFO | ldamodel.py:1171 | show_topics | topic #1 (0.260): 0.029*"wfh" + 0.027*"offer" + 0.024*"setup" + 0.019*"account" + 0.015*"salary" + 0.011*"basic" + 0.010*"career" + 0.010*"shift" + 0.010*"employee" + 0.010*"handle"
2022-12-21 09:28:20,100 | INFO | ldamodel.py:1171 | show_topics | topic #2 (0.195): 0.039*"good" + 0.023*"increase" + 0.016*"salary" + 0.015*"experience" + 0.012*"environment" + 0.012*"gain" + 0.010*"culture" + 0.009*"schedule" + 0.009*"working" + 0.009*"annual"
2022-12-21 09:28:20,101 | INFO | ldamodel.py:1171 | show_topics | topic #3 (0.156): 0.015*"go" + 0.013*"salary" + 0.012*"work" + 0.012*"friend" + 0.012*"back" + 0.012*"site" + 0.012*"wfh" + 0.009*"company" + 0.009*"also" + 0.009*"consider"
2022-12-21 09:28:20,102 | INFO | ldamodel.py:1049 | do_mstep | topic diff=0.016663, rho=0.376089
2022-12-21 09:28:20,106 | INFO | ldamodel.py:822 | log_perplexity | -5.946 per-word bound, 61.7 perplexity estimate based on a held-out corpus of 7 documents with 28 words
2022-12-21 09:28:20,107 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 6, dispatched chunk #0 = documents up to #100/107, outstanding queue size 1
2022-12-21 09:28:20,108 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 6, dispatched chunk #1 = documents up to #107/107, outstanding queue size 2
2022-12-21 09:28:20,131 | INFO | ldamodel.py:1171 | show_topics | topic #0 (0.390): 0.047*"good" + 0.036*"company" + 0.024*"benefit" + 0.023*"salary" + 0.017*"friend" + 0.016*"people" + 0.015*"compensation" + 0.015*"refer" + 0.014*"high" + 0.012*"employee"
2022-12-21 09:28:20,132 | INFO | ldamodel.py:1171 | show_topics | topic #1 (0.260): 0.029*"wfh" + 0.027*"offer" + 0.024*"setup" + 0.019*"account" + 0.014*"salary" + 0.011*"career" + 0.010*"basic" + 0.010*"shift" + 0.010*"handle" + 0.010*"employee"
2022-12-21 09:28:20,133 | INFO | ldamodel.py:1171 | show_topics | topic #2 (0.195): 0.039*"good" + 0.024*"increase" + 0.016*"salary" + 0.015*"experience" + 0.012*"environment" + 0.012*"gain" + 0.011*"culture" + 0.009*"schedule" + 0.009*"working" + 0.009*"annual"
2022-12-21 09:28:20,133 | INFO | ldamodel.py:1171 | show_topics | topic #3 (0.156): 0.015*"go" + 0.012*"work" + 0.012*"salary" + 0.012*"site" + 0.012*"wfh" + 0.012*"back" + 0.011*"friend" + 0.009*"also" + 0.009*"consider" + 0.009*"mother"
2022-12-21 09:28:20,134 | INFO | ldamodel.py:1049 | do_mstep | topic diff=0.012892, rho=0.352017
2022-12-21 09:28:20,138 | INFO | ldamodel.py:822 | log_perplexity | -5.952 per-word bound, 61.9 perplexity estimate based on a held-out corpus of 7 documents with 28 words
2022-12-21 09:28:20,139 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 7, dispatched chunk #0 = documents up to #100/107, outstanding queue size 1
2022-12-21 09:28:20,140 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 7, dispatched chunk #1 = documents up to #107/107, outstanding queue size 2
2022-12-21 09:28:20,163 | INFO | ldamodel.py:1171 | show_topics | topic #0 (0.390): 0.047*"good" + 0.037*"company" + 0.024*"benefit" + 0.023*"salary" + 0.017*"friend" + 0.016*"people" + 0.015*"compensation" + 0.015*"refer" + 0.014*"high" + 0.012*"employee"
2022-12-21 09:28:20,164 | INFO | ldamodel.py:1171 | show_topics | topic #1 (0.260): 0.029*"wfh" + 0.027*"offer" + 0.024*"setup" + 0.020*"account" + 0.014*"salary" + 0.011*"career" + 0.010*"basic" + 0.010*"shift" + 0.010*"handle" + 0.010*"employee"
2022-12-21 09:28:20,164 | INFO | ldamodel.py:1171 | show_topics | topic #2 (0.195): 0.038*"good" + 0.024*"increase" + 0.015*"salary" + 0.015*"experience" + 0.012*"environment" + 0.012*"gain" + 0.011*"culture" + 0.009*"schedule" + 0.009*"annual" + 0.009*"pay"
2022-12-21 09:28:20,165 | INFO | ldamodel.py:1171 | show_topics | topic #3 (0.156): 0.015*"go" + 0.012*"site" + 0.012*"wfh" + 0.012*"back" + 0.012*"work" + 0.011*"friend" + 0.011*"salary" + 0.009*"also" + 0.009*"mother" + 0.009*"consider"
2022-12-21 09:28:20,166 | INFO | ldamodel.py:1049 | do_mstep | topic diff=0.009879, rho=0.332045
2022-12-21 09:28:20,170 | INFO | ldamodel.py:822 | log_perplexity | -5.956 per-word bound, 62.1 perplexity estimate based on a held-out corpus of 7 documents with 28 words
2022-12-21 09:28:20,171 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 8, dispatched chunk #0 = documents up to #100/107, outstanding queue size 1
2022-12-21 09:28:20,172 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 8, dispatched chunk #1 = documents up to #107/107, outstanding queue size 2
2022-12-21 09:28:20,195 | INFO | ldamodel.py:1171 | show_topics | topic #0 (0.390): 0.048*"good" + 0.037*"company" + 0.024*"salary" + 0.023*"benefit" + 0.017*"friend" + 0.016*"people" + 0.015*"compensation" + 0.015*"refer" + 0.014*"high" + 0.012*"employee"
2022-12-21 09:28:20,196 | INFO | ldamodel.py:1171 | show_topics | topic #1 (0.260): 0.029*"wfh" + 0.027*"offer" + 0.024*"setup" + 0.020*"account" + 0.014*"salary" + 0.012*"career" + 0.010*"basic" + 0.010*"shift" + 0.010*"handle" + 0.010*"employee"
2022-12-21 09:28:20,197 | INFO | ldamodel.py:1171 | show_topics | topic #2 (0.195): 0.038*"good" + 0.024*"increase" + 0.015*"salary" + 0.015*"experience" + 0.012*"gain" + 0.012*"environment" + 0.011*"culture" + 0.009*"schedule" + 0.009*"annual" + 0.009*"pay"
2022-12-21 09:28:20,197 | INFO | ldamodel.py:1171 | show_topics | topic #3 (0.156): 0.015*"go" + 0.012*"site" + 0.012*"wfh" + 0.012*"back" + 0.011*"work" + 0.011*"friend" + 0.010*"salary" + 0.009*"also" + 0.009*"mother" + 0.009*"consider"
2022-12-21 09:28:20,198 | INFO | ldamodel.py:1049 | do_mstep | topic diff=0.008555, rho=0.315127
2022-12-21 09:28:20,202 | INFO | ldamodel.py:822 | log_perplexity | -5.958 per-word bound, 62.2 perplexity estimate based on a held-out corpus of 7 documents with 28 words
2022-12-21 09:28:20,202 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 9, dispatched chunk #0 = documents up to #100/107, outstanding queue size 1
2022-12-21 09:28:20,204 | INFO | ldamulticore.py:294 | update | PROGRESS: pass 9, dispatched chunk #1 = documents up to #107/107, outstanding queue size 2
2022-12-21 09:28:20,227 | INFO | ldamodel.py:1171 | show_topics | topic #0 (0.390): 0.048*"good" + 0.038*"company" + 0.025*"salary" + 0.023*"benefit" + 0.017*"friend" + 0.016*"people" + 0.015*"compensation" + 0.014*"high" + 0.014*"refer" + 0.012*"employee"
2022-12-21 09:28:20,228 | INFO | ldamodel.py:1171 | show_topics | topic #1 (0.260): 0.029*"wfh" + 0.027*"offer" + 0.024*"setup" + 0.020*"account" + 0.014*"salary" + 0.012*"career" + 0.010*"basic" + 0.010*"shift" + 0.010*"handle" + 0.010*"increase"
2022-12-21 09:28:20,228 | INFO | ldamodel.py:1171 | show_topics | topic #2 (0.195): 0.038*"good" + 0.024*"increase" + 0.015*"experience" + 0.015*"salary" + 0.012*"gain" + 0.012*"environment" + 0.012*"culture" + 0.009*"schedule" + 0.009*"annual" + 0.009*"pay"
2022-12-21 09:28:20,229 | INFO | ldamodel.py:1171 | show_topics | topic #3 (0.156): 0.015*"go" + 0.012*"site" + 0.012*"wfh" + 0.012*"back" + 0.011*"friend" + 0.011*"work" + 0.009*"salary" + 0.009*"also" + 0.009*"mother" + 0.009*"consider"
2022-12-21 09:28:20,230 | INFO | ldamodel.py:1049 | do_mstep | topic diff=0.008456, rho=0.300557
2022-12-21 09:28:20,234 | INFO | ldamodel.py:822 | log_perplexity | -5.960 per-word bound, 62.2 perplexity estimate based on a held-out corpus of 7 documents with 28 words

> 4) Visualizing topics

For (1), you can manually select each topic to view its top most frequent and/or “relevant” terms, using different values of the λ parameter. This can help when you’re trying to assign a human interpretable name or “meaning” to each topic.

For (2), exploring the Intertopic Distance Plot can help you learn about how topics relate to each other, including potential higher-level structure between groups of topics.

**Interpretation:**


*Bar chart*
- Each bubble represents a topic. The larger the bubble, the higher percentage of the number of responses in the corpus is about that topic.
- Blue bars represent the overall frequency of each word in the corpus. If no topic is selected, the blue bars of the most frequently used words will be displayed.
- Red bars give the estimated number of times a given term was generated by a given topic. The word with the longest red bar is the word that is used the most by the responses belonging to that topic.
- <u>*Lambda*</u> -- Decreasing the lambda parameter, increases the weight of the ratio of the frequency of word given the topic / Overall frequency of the word in the documents. Important words for the given topic moves upward.
    - Lambda = 1, top words by frequency
    - Lambda = 0, top words by relevance to topic

*Bubble plot*
- The further the bubbles are away from each other, the more different they are. 
- The larger the bubble, the more frequent is the topic in the documents.
- Distance between the topics is an approximation of semantic relationship between the topics.
- The topic which shares common words will be overlapping (closer in distance) in comparison to the non-overlapping topic.
- A good topic model will have big and non-overlapping bubbles scattered throughout the chart. As we can see from the graph, the bubbles are clustered within one place.
- A topic model with a low number of topics will have big non-overlapping bubbles, scattered throughout the chart whereas, the topic model with a high number of topics, will have many overlapping small size bubbles, clustered in the chart.

In [25]:
import pyLDAvis.gensim
import pickle 
import pyLDAvis

In [26]:
# Visualize the topics
pyLDAvis.enable_notebook()
LDAvis_prepared = pyLDAvis.gensim.prepare(lda_model, corpus, id2word)
LDAvis_prepared = pyLDAvis.gensim.prepare(lda_model, corpus, id2word)
LDAvis_prepared

/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic
0      0.065469 -0.013488       1        1  46.291119
1     -0.047821 -0.016587       2        1  25.737310
2      0.001400  0.032408       3        1  14.091917
3     -0.019047 -0.002333       4        1  13.879655, topic_info=         Term       Freq      Total Category  logprob  loglift
38       good  19.000000  19.000000  Default  30.0000  30.0000
18        wfh   6.000000   6.000000  Default  29.0000  29.0000
173  increase   4.000000   4.000000  Default  28.0000  28.0000
17      setup   5.000000   5.000000  Default  27.0000  27.0000
15      offer   6.000000   6.000000  Default  26.0000  26.0000
..        ...        ...        ...      ...      ...      ...
46     salary   0.832442  11.919428   Topic4  -4.6794  -0.6868
35   employee   0.606213   6.187447   Topic4  -4.9966  -0.3483
91     people   0.544451   6.012559   Topic4  -5.1040  -0.4271
28       want   0.532789   2.790287   Topic4  -5.1257   0.3190
11       wise   0.532610   2.063286   Topic4  -5.1260   0.6205

[196 rows x 6 columns], token_table=      Topic      Freq           Term
term
79        1  0.597130  accommodation
79        4  0.597130  accommodation
12        1  0.205943        account
12        2  0.617829        account
12        3  0.205943        account
...     ...       ...            ...
115       3  0.193465        working
78        1  0.569677          would
78        2  0.284839          would
78        3  0.284839          would
78        4  0.284839          would

[299 rows x 3 columns], R=30, lambda_step=0.01, plot_opts={'xlab': 'PC1', 'ylab': 'PC2'}, topic_order=[1, 2, 3, 4])

# Post-modeling Exploratory Data Analysis

*Assign respondents to their topic clusters*

In [27]:
# Topic distribution for the whole document. Each element in the list is a pair of a topic’s id, and the probability that was assigned to it.
topic_dist = list(lda_model.get_document_topics(corpus))


# Classify responses to topics
cluster = []
probability = []

for i in range(0, len(topic_dist)):
    clust = [x for x,y in topic_dist[i]]
    prob = [y for x,y in topic_dist[i]]
    get_index = prob.index(max(prob))
    max_val = topic_dist[i][get_index]
    cluster.append(max_val[0])
    probability.append(max_val[1])
    
# Add classification to df
analysis_df['Topic'] = cluster
analysis_df['Topic_Probability'] = probability

/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [28]:
# Map topics to Oracle ID
id_topic_mapper = dict(zip(analysis_df['Oracle ID of former employee'], analysis_df['Topic']))
id_prob_mapper = dict(zip(analysis_df['Oracle ID of former employee'], analysis_df['Topic_Probability']))
id_rate_mapper = dict(zip(analysis_df['Oracle ID of former employee'], analysis_df['How would you rate your overall experience with TTEC on a scale of 1 to 5? 5 being Very Good and 1 being Not Good']))

# For those with missing Oracle ID, map to names
name_mapper = (analysis_df[~analysis_df.applymap(np.isreal)['Oracle ID of former employee']]
               .assign(Name = lambda x: x['Name of former employee'].apply(lambda x: x.upper()))
               [['Name','Topic']]
                
                     .set_index("Name").to_dict()['Topic']
)

name_mapper2 = (analysis_df[~analysis_df.applymap(np.isreal)['Oracle ID of former employee']]
               .assign(Name = lambda x: x['Name of former employee'].apply(lambda x: x.upper()))
               [['Name','Topic_Probability']]
                
                     .set_index("Name").to_dict()['Topic_Probability']
)

rating_mapper = (analysis_df[~analysis_df.applymap(np.isreal)['Oracle ID of former employee']]
               .assign(Name = lambda x: x['Name of former employee'].apply(lambda x: x.upper()))
               [['Name','How would you rate your overall experience with TTEC on a scale of 1 to 5? 5 being Very Good and 1 being Not Good']]
                
                     .set_index("Name").to_dict()['How would you rate your overall experience with TTEC on a scale of 1 to 5? 5 being Very Good and 1 being Not Good']
)

# Filter attrition df to contain respondents only
respondents_demog_df = (attrition_df
                         .assign(Topic1 = lambda x: x['EE Oracle Id'].map(id_topic_mapper),
                                 Prob1 = lambda x: x['EE Oracle Id'].map(id_prob_mapper),
                                 Rate1 = lambda x: x['EE Oracle Id'].map(id_rate_mapper),
                                 Name = lambda x: (x['First Name'] + " " + x['Last Name']).apply(lambda x: x.upper()),
                                 Topic = lambda x: np.where(x['Topic1'].isna(), x['Name'].map(name_mapper), x['Topic1']),
                                 Topic_Probability = lambda x: np.where(x['Prob1'].isna(), x['Name'].map(name_mapper2), x['Prob1']),
                                Rating = lambda x: np.where(x['Rate1'].isna(), x['Name'].map(rating_mapper), x['Rate1']),

                         )
                         .drop(['Topic1','Prob1','Rate1'], axis = 1)
                         .query("Topic.notna()", engine = 'python')
                         .sort_values(by = 'Topic')
                        )

/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

> 1) How many respondents belong to each topic cluster & what is the average probability score?

In [29]:
# "Number of Employees per Cluster & Average Probability Score")
gen_stats = (analysis_df
             .groupby(['Topic']).agg({'Oracle ID of former employee':'nunique', 'Topic_Probability':'describe'})
             .reset_index()
            )

gen_stats

print("Number of Employees per Cluster & Average Probability Score")

/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

  Topic Oracle ID of former employee Topic_Probability                      \
        Oracle ID of former employee             count      mean       std
0     0                           59              59.0  0.855169  0.107034
1     1                           26              26.0  0.836349  0.089500
2     2                           14              14.0  0.823973  0.112651
3     3                            8               8.0  0.802365  0.186979


        min       25%       50%       75%       max
0  0.389610  0.844225  0.876585  0.922368  0.965419
1  0.564469  0.811484  0.849177  0.886963  0.970229
2  0.507118  0.774359  0.865088  0.905642  0.924618
3  0.471947  0.726776  0.881270  0.937067  0.958676

Number of Employees per Cluster & Average Probability Score

> 2) Tenure, Topic Probability, and Employee Count by By Attrition Stage

In [30]:
(respondents_demog_df
 .groupby(['Topic','Stage Attrition']).agg({'EE Oracle Id':'nunique','Tenure In Months':['mean', 'std','median'],'Topic_Probability':['mean', 'std','median']})
 .unstack('Stage Attrition')
)

/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

                  EE Oracle Id            Tenure In Months             \
                       nunique                        mean
Stage Attrition Pre Production Production   Pre Production Production
Topic
0.0                          8         51         7.625000  26.470588
1.0                          3         23         3.666667  20.521739
2.0                          1         13         1.000000  35.461538
3.0                          2          6         1.000000  16.666667

                                                                     \
                           std                    median
Stage Attrition Pre Production Production Pre Production Production
Topic
0.0                  11.312919  23.479653            2.0       20.0
1.0                   1.527525  14.534816            4.0       21.0
2.0                        NaN  22.976856            1.0       34.0
3.0                   0.000000  17.443241            1.0       12.0

                Topic_Probability                                       \
                             mean                       std
Stage Attrition    Pre Production Production Pre Production Production
Topic
0.0                      0.883937   0.850656       0.048643   0.113158
1.0                      0.878693   0.830826       0.033703   0.093397
2.0                      0.915059   0.816966            NaN   0.114031
3.0                      0.912539   0.765640       0.065248   0.204010


                        median
Stage Attrition Pre Production Production
Topic
0.0                   0.894370   0.876303
1.0                   0.871612   0.849143
2.0                   0.915059   0.857148
3.0                   0.912539   0.839274

> 3) Tenure, Topic Probability, and Employee Count by By Job Name

In [31]:
(respondents_demog_df
 .groupby(['Topic','Job Name','Stage Attrition']).agg({'EE Oracle Id':'nunique','Tenure In Months':['mean', 'std','median']})
 .unstack('Job Name')
)

/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

                      EE Oracle Id                                        \
                           nunique
Job Name                     CSR I CSR II CSR III Chat Sales Associate I
Topic Stage Attrition
0.0   Pre Production           3.0    5.0     NaN                    NaN
      Production               9.0   30.0     8.0                    NaN
1.0   Pre Production           3.0    NaN     NaN                    NaN
      Production               1.0   19.0     1.0                    1.0
2.0   Pre Production           NaN    1.0     NaN                    NaN
      Production               2.0    8.0     3.0                    NaN
3.0   Pre Production           NaN    2.0     NaN                    NaN
      Production               1.0    4.0     1.0                    NaN

                                          Tenure In Months             \
                                                      mean
Job Name              ISR I TSR I TSR III            CSR I     CSR II
Topic Stage Attrition
0.0   Pre Production    NaN   NaN     NaN         2.000000  11.000000
      Production        NaN   1.0     3.0        29.444444  24.700000
1.0   Pre Production    NaN   NaN     NaN         3.666667        NaN
      Production        1.0   NaN     NaN        27.000000  17.368421
2.0   Pre Production    NaN   NaN     NaN              NaN   1.000000
      Production        NaN   NaN     NaN        32.500000  42.625000
3.0   Pre Production    NaN   NaN     NaN              NaN   1.000000
      Production        NaN   NaN     NaN        49.000000   7.500000

                                                                     \

Job Name                 CSR III Chat Sales Associate I ISR I TSR I
Topic Stage Attrition
0.0   Pre Production         NaN                    NaN   NaN   NaN
      Production       28.750000                    NaN   NaN  56.0
1.0   Pre Production         NaN                    NaN   NaN   NaN
      Production       16.000000                   40.0  59.0   NaN
2.0   Pre Production         NaN                    NaN   NaN   NaN
      Production       18.333333                    NaN   NaN   NaN
3.0   Pre Production         NaN                    NaN   NaN   NaN
      Production       21.000000                    NaN   NaN   NaN

                                                                   \
                                        std
Job Name                 TSR III      CSR I     CSR II    CSR III
Topic Stage Attrition
0.0   Pre Production         NaN   1.000000  13.619838        NaN
      Production       19.333333  21.651277  27.044217  13.328273
1.0   Pre Production         NaN   1.527525        NaN        NaN
      Production             NaN        NaN  11.870648        NaN
2.0   Pre Production         NaN        NaN        NaN        NaN
      Production             NaN  12.020815  24.088750  20.256686
3.0   Pre Production         NaN        NaN   0.000000        NaN
      Production             NaN        NaN   6.350853        NaN

                                                                           \
                                                                   median
Job Name              Chat Sales Associate I ISR I TSR I   TSR III  CSR I
Topic Stage Attrition
0.0   Pre Production                     NaN   NaN   NaN       NaN    2.0
      Production                         NaN   NaN   NaN  7.767453   21.0
1.0   Pre Production                     NaN   NaN   NaN       NaN    4.0
      Production                         NaN   NaN   NaN       NaN   27.0
2.0   Pre Production                     NaN   NaN   NaN       NaN    NaN
      Production                         NaN   NaN   NaN       NaN   32.5
3.0   Pre Production                     NaN   NaN   NaN       NaN    NaN
      Production                         NaN   NaN   NaN       NaN   49.0

                                                                         \

Job Name              CSR II CSR III Chat Sales Associate I ISR I TSR I
Topic Stage Attrition
0.0   Pre Production     2.0     NaN                    NaN   NaN   NaN
      Production        17.5    23.0                    NaN   NaN  56.0
1.0   Pre Production     NaN     NaN                    NaN   NaN   NaN
      Production        19.0    16.0                   40.0  59.0   NaN
2.0   Pre Production     1.0     NaN                    NaN   NaN   NaN
      Production        35.5    12.0                    NaN   NaN   NaN
3.0   Pre Production     1.0     NaN                    NaN   NaN   NaN
      Production         6.5    21.0                    NaN   NaN   NaN



Job Name              TSR III
Topic Stage Attrition
0.0   Pre Production      NaN
      Production         17.0
1.0   Pre Production      NaN
      Production          NaN
2.0   Pre Production      NaN
      Production          NaN
3.0   Pre Production      NaN
      Production          NaN

> 4) Tenure, Topic Probability, and Employee Count by By Job Name

In [32]:
(respondents_demog_df
 .groupby(['Topic','Stage Attrition']).agg({'Rating': ['mean', 'std','median']})
 .round(1)
)

/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

                      Rating
                        mean  std median
Topic Stage Attrition
0.0   Pre Production     4.3  0.8    4.0
      Production         4.2  0.7    4.0
1.0   Pre Production     4.0  1.4    4.0
      Production         4.0  1.1    4.0
2.0   Pre Production     5.0  NaN    5.0
      Production         4.3  0.6    4.0
3.0   Pre Production     3.0  NaN    3.0
      Production         4.2  0.5    4.0